import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const port=8897,tmp=fs.mkdtempSync(path.join(os.tmpdir(),'bilio-auth-')),dbPath=path.join(tmp,'data.json');let proc;
const wait=async()=>{for(let i=0;i<60;i++){try{const r=await fetch(`http://127.0.0.1:${port}/api/me`);if(r.status===401)return}catch{}await new Promise(r=>setTimeout(r,50))}throw new Error('API başlamadı')};
const json=async(url,opt={})=>{const r=await fetch(`http://127.0.0.1:${port}${url}`,opt);return [r,await r.json()]};
test.before(async()=>{proc=spawn(process.execPath,['server/auth-server.mjs'],{cwd:process.cwd(),env:{...process.env,BILIO_API_PORT:String(port),BILIO_DB_PATH:dbPath},stdio:'ignore'});await wait()});
test.after(()=>{proc?.kill();fs.rmSync(tmp,{recursive:true,force:true})});

test('misafir oyun API erişimi reddedilir',async()=>{const [r,j]=await json('/api/game/vampire/active');assert.equal(r.status,401);assert.equal(j.error,'Giriş gerekli.')});
test('kayıt ödülü, mesaj ve bildirim tek işlemde oluşturulur',async()=>{const [r,j]=await json('/api/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'TestOyuncu',password:'Guvenli123',passwordRepeat:'Guvenli123'})});assert.equal(r.status,201);assert.equal(j.user.gold,5000);assert.equal(j.user.diamonds,1000);assert.equal(j.user.unreadMessages,1);assert.equal(j.user.unreadNotifications,1);assert.equal(j.user.level,1);const cookie=r.headers.get('set-cookie').split(';')[0];const [mr,mj]=await json('/api/messages',{headers:{cookie}});assert.equal(mr.status,200);assert.equal(mj.items.length,1);assert.match(mj.items[0].body,/Bilio dünyasında/);const [nr,nj]=await json('/api/notifications',{headers:{cookie}});assert.equal(nr.status,200);assert.equal(nj.items.length,1);const [rr]=await json(`/api/messages/${mj.items[0].id}/read`,{method:'POST',headers:{cookie}});assert.equal(rr.status,200);const [me,mej]=await json('/api/me',{headers:{cookie}});assert.equal(me.status,200);assert.equal(mej.user.unreadMessages,0);assert.equal(mej.user.gold,5000);});
test('aynı kullanıcı adı büyük küçük harf farkıyla tekrar alınamaz',async()=>{const [r]=await json('/api/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'testoyuncu',password:'Guvenli123',passwordRepeat:'Guvenli123'})});assert.equal(r.status,409)});
test('yanlış şifre güvenli hata döndürür',async()=>{const [r,j]=await json('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'TestOyuncu',password:'yanlis123'})});assert.equal(r.status,401);assert.equal(j.error,'Kullanıcı adı veya şifre hatalı.')});
