import test from 'node:test';
import assert from 'node:assert/strict';
import {HANGMAN_LETTER_COST,addHangmanBots,buyHangmanLetter,createHangmanRoom,guessHangmanLetter,publicHangmanRoom,startHangman,tickHangman,updateHangmanSettings} from '../server/hangman-store.mjs';

const host={id:'hangman-host',username:'Oyuncu',level:12,selectedTitleId:'title-1',profile:{avatarUrl:'',selectedFrameId:null}};
test('Adam Asmaca odası AA kodu ve sekiz koltukla açılır',()=>{const room=createHangmanRoom(host);assert.match(room.code,/^AA-\d{4}$/);assert.equal(room.capacity,8);assert.equal(room.players.length,1)});
test('yalnızca kurucu ayar değiştirir ve bot davet eder',()=>{const room=createHangmanRoom({...host,id:'hangman-settings'});assert.throws(()=>updateHangmanSettings(room,'başkası',{roundCount:5}),/kurucu/);updateHangmanSettings(room,host.id.replace('host','settings'),{category:'HAYVANLAR',roundCount:5,turnSeconds:15});assert.equal(room.roundCount,5);assert.equal(addHangmanBots(room,room.hostUserId),7);assert.equal(room.players.length,8)});
test('harf tahmini sunucuda doğrulanır ve aynı harf tekrarlanamaz',()=>{const room=createHangmanRoom({...host,id:'hangman-guess'});startHangman(room,room.hostUserId,1000);const first=room.game.word[0];const result=guessHangmanLetter(room,room.hostUserId,first,1100);assert.equal(result.correct,true);assert.throws(()=>guessHangmanLetter(room,room.hostUserId,first,1200),/daha önce/)});
test('yanlış harf sırayı geçirir',()=>{const room=createHangmanRoom({...host,id:'hangman-turn'});addHangmanBots(room,room.hostUserId);startHangman(room,room.hostUserId,1000);const wrong='ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ'.split('').find(letter=>!room.game.word.includes(letter));guessHangmanLetter(room,room.hostUserId,wrong,1100);assert.notEqual(room.game.activeUserId,room.hostUserId)});
test('donut harf satın alma daha önce açılmamış gerçek harf verir',()=>{const room=createHangmanRoom({...host,id:'hangman-buy'});startHangman(room,room.hostUserId,1000);const result=buyHangmanLetter(room,room.hostUserId,1100);assert.equal(result.cost,HANGMAN_LETTER_COST);assert.ok(room.game.word.includes(result.letter));assert.ok(room.game.guessed.includes(result.letter))});
test('süre dolunca sıra güvenle ilerler ve botlar hamle yapar',()=>{const room=createHangmanRoom({...host,id:'hangman-bot'});addHangmanBots(room,room.hostUserId);startHangman(room,room.hostUserId,1000);tickHangman(room,room.game.turnEndsAt+1);const botId=room.game.activeUserId;assert.match(botId,/^bot-/);tickHangman(room,room.game.turnStartedAt+1500);const state=publicHangmanRoom(room);assert.ok(state.game.guessed.length+state.game.wrong.length>=1)});
