import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {createRoom,roomByCode,roomForUser,joinRoom,leaveRoom,toggleReady,publicRoom,matches,privateMatch,invites,finishVote} from './vampire-store.mjs';

const PORT=Number(process.env.BILIO_API_PORT||8787),dbPath=path.resolve(process.env.BILIO_DB_PATH||'server/data.json');
fs.mkdirSync(path.dirname(dbPath),{recursive:true});let db={users:[],sessions:{},lobbyMessages:[],lobbyInvites:[],transactions:[],weeklyArchives:[],meta:{}};try{db={...db,...JSON.parse(fs.readFileSync(dbPath,'utf8'))}}catch{}
db.users ||= [];db.sessions ||= {};db.lobbyMessages ||= [];db.lobbyInvites ||= [];db.transactions ||= [];db.weeklyArchives ||= [];db.meta ||= {};
const nowIso=()=>new Date().toISOString();
for(const u of db.users){u.gold??=0;u.diamonds??=0;u.messages??=[];u.notifications??=[];u.level??=1;u.xp??=0;u.selectedTitleId??='title-1';u.inventory??=[];u.profile??={};u.profile.about??='';u.profile.avatarUrl??='';u.profile.selectedFrameId??=null;u.profile.selectedBadgeIds??=[];u.profile.badges??=[];u.profile.gifts??=[];u.profile.achievements??=[];u.stats??={matches:0,wins:0,correct:0,score:0};u.weekly??={score:0,victories:0,updatedAt:null};}
const save=()=>{const tmp=dbPath+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,dbPath)};
const reserved=new Set(['admin','administrator','system','biliobot']),attempts=new Map(),rateMap=new Map(),sse=new Set();
const norm=s=>String(s||'').trim().toLocaleLowerCase('tr-TR').replace(/ı/g,'i');
const hash=p=>new Promise((ok,no)=>{const salt=crypto.randomBytes(16);crypto.scrypt(p,salt,64,(e,k)=>e?no(e):ok(`${salt.toString('hex')}:${k.toString('hex')}`))});
const verify=(p,h)=>new Promise(ok=>{const [s,k]=String(h||'').split(':');if(!s||!k)return ok(false);crypto.scrypt(p,Buffer.from(s,'hex'),64,(e,d)=>ok(!e&&d.length===Buffer.from(k,'hex').length&&crypto.timingSafeEqual(d,Buffer.from(k,'hex'))))});
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=')));
const publicUser=u=>({id:u.id,username:u.username,level:u.level,xp:u.xp,selectedTitleId:u.selectedTitleId,gold:u.gold,diamonds:u.diamonds,unreadMessages:u.messages.filter(x=>!x.readAt).length,unreadNotifications:u.notifications.filter(x=>!x.readAt).length});
function send(res,status,obj,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(obj))}
async function body(req,max=8_000_000){let s='';for await(const c of req){s+=c;if(s.length>max)throw Error('İstek çok büyük.')}return JSON.parse(s||'{}')}
const clean=(s,max=500)=>String(s||'').trim().slice(0,max).replace(/[<>]/g,'');
const rate=(key,ms=700,msg='Çok hızlı mesaj gönderiyorsunuz. Lütfen biraz bekleyin.')=>{const n=Date.now(),last=rateMap.get(key)||0;if(n-last<ms)throw Error(msg);rateMap.set(key,n)};
const broadcast=item=>{const data=`data: ${JSON.stringify({type:'lobby-item',item})}\n\n`;for(const r of sse){try{r.write(data)}catch{sse.delete(r)}}};
function currentWeekKey(){const shifted=new Date(Date.now()+3*3600_000),day=(shifted.getUTCDay()+6)%7,monday=new Date(Date.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth(),shifted.getUTCDate()-day));return monday.toISOString().slice(0,10)}
function rollover(){const key=currentWeekKey();if(!db.meta.weekKey){db.meta.weekKey=key;save();return}if(db.meta.weekKey===key)return;const old=db.meta.weekKey;db.weeklyArchives.push({weekKey:old,closedAt:nowIso(),rows:db.users.filter(u=>u.weekly?.score>0).map(u=>({userId:u.id,score:u.weekly.score,victories:u.weekly.victories||0}))});for(const u of db.users)u.weekly={score:0,victories:0,updatedAt:null};db.meta.weekKey=key;save()}
rollover();setInterval(rollover,60_000).unref();
const titleUnlock=id=>{const n=Number(String(id).match(/(\d+)/)?.[1]||1);return 1+(n-1)*20};
const titleIds=u=>Array.from({length:25},(_,i)=>`title-${i+1}`).filter(id=>titleUnlock(id)<=u.level);
const nextLevelXp=level=>Math.min(500,level)>=500?0:Math.max(1000,level*500-2000);
const catalog=[
 {id:'emoji-gulen',category:'EMOJİLER',name:'Gülen Donut',price:250,currency:'gold',preview:'🍩'}, {id:'emoji-goz',category:'EMOJİLER',name:'Göz Kırpan',price:200,currency:'gold',preview:'😉'}, {id:'emoji-onay',category:'EMOJİLER',name:'Parmakla Onay',price:200,currency:'gold',preview:'👍'}, {id:'emoji-kalp',category:'EMOJİLER',name:'Kalp',price:150,currency:'gold',preview:'❤️'}, {id:'emoji-parti',category:'EMOJİLER',name:'Parti',price:300,currency:'gold',preview:'🎉'}, {id:'emoji-yildiz',category:'EMOJİLER',name:'Gülen Yıldız',price:250,currency:'gold',preview:'⭐'},
 ...Array.from({length:25},(_,i)=>({id:`title-${i+1}`,category:'UNVANLAR',name:['ACEMİ','ÇAYLAK','YOLCU','KAŞİF','OYUNCU','YETENEKLİ','USTA','UZMAN','STRATEJİST','BİLGE','ELİT','SEÇKİN','ŞAMPİYON','KAHRAMAN','YILDIZ','EFSANE ADAYI','BÜYÜK USTA','ZİRVE','KOZMİK','TAHT VARİSİ','YÜCE','ÖLÜMSÜZ','MİTİK','EFSANEVİ','LEGEND'][i],price:0,currency:'gold',preview:'',assetPath:`/titles/assets/title-${String(i+1).padStart(2,'0')}-${['acemi','caylak','yolcu','kasif','oyuncu','yetenekli','usta','uzman','stratejist','bilge','elit','seckin','sampiyon','kahraman','yildiz','efsane-adayi','buyuk-usta','zirve','kozmik','taht-varisi','yuce','olumsuz','mitik','efsanevi','legend'][i]}.png`,requiredLevel:1+i*20,unlockOnly:true})),
 {id:'frame-baslangic',category:'ÇERÇEVELER',name:'Başlangıç Çerçevesi',price:500,currency:'gold',preview:'◉'}, {id:'frame-karamel',category:'ÇERÇEVELER',name:'Karamel Çerçeve',price:800,currency:'gold',preview:'◎'},
 {id:'badge-ilk',category:'ROZETLER',name:'İlk Adım',price:0,currency:'gold',preview:'✦',unlockOnly:true},
 {id:'gift-kutu',category:'HEDİYELER',name:'Hediye Kutusu',price:120,currency:'diamonds',preview:'🎁',consumable:true},
 {id:'boost-xp',category:'TAKVİYELER',name:'XP Takviyesi',price:200,currency:'diamonds',preview:'⚡',consumable:true}
];
function productFor(u,p){const inv=u?.inventory?.find(x=>x.productId===p.id);const titleOwned=p.category==='UNVANLAR'&&u&&p.requiredLevel<=u.level;return {...p,owned:!!inv||!!titleOwned,equipped:p.category==='UNVANLAR'?u?.selectedTitleId===p.id:p.category==='ÇERÇEVELER'?u?.profile?.selectedFrameId===p.id:false,quantity:inv?.quantity||0}}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://x');if(!url.pathname.startsWith('/api/'))return send(res,404,{error:'Bulunamadı.'});const sid=cookies(req).bilio_session,uid=sid&&db.sessions[sid]?.userId,me=db.users.find(u=>u.id===uid);
 if(url.pathname==='/api/lobby/events'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(': bağlı\n\n');sse.add(res);req.on('close',()=>sse.delete(res));return}
 if(url.pathname==='/api/me'&&req.method==='GET')return me?send(res,200,{user:publicUser(me)}):send(res,401,{error:'Oturum yok.'});
 if(url.pathname==='/api/register'&&req.method==='POST'){const ip=req.socket.remoteAddress||'x',now=Date.now(),key='register:'+ip,a=(attempts.get(key)||[]).filter(t=>now-t<60000);if(a.length>=6)return send(res,429,{error:'Çok fazla kayıt denemesi. Biraz sonra tekrar deneyin.'});a.push(now);attempts.set(key,a);const b=await body(req),raw=String(b.username||'').trim(),n=norm(raw);if(!raw)return send(res,400,{error:'Kullanıcı adı zorunludur.'});if(n.length<3||n.length>20||!/^[-_\p{L}\p{N}]+$/u.test(raw)||reserved.has(n))return send(res,400,{error:'Kullanıcı adı 3–20 karakter olmalı ve harf, rakam, tire veya alt çizgi içermelidir.'});if(db.users.some(u=>u.usernameNormalized===n))return send(res,409,{error:'Bu kullanıcı adı zaten kullanılıyor.'});if(typeof b.password!=='string'||b.password.length<8||b.password.length>128)return send(res,400,{error:'Şifre en az 8 karakter olmalıdır.'});if(b.password!==b.passwordRepeat)return send(res,400,{error:'Şifreler eşleşmiyor.'});const createdAt=nowIso(),u={id:crypto.randomUUID(),username:raw,usernameNormalized:n,passwordHash:await hash(b.password),createdAt,lastLoginAt:createdAt,level:1,xp:0,selectedTitleId:'title-1',gold:5000,diamonds:1000,registrationRewardGranted:true,profile:{about:'',avatarUrl:'',selectedFrameId:null,selectedBadgeIds:[],badges:[],gifts:[],achievements:[]},inventory:[],stats:{matches:0,wins:0,correct:0,score:0},weekly:{score:0,victories:0,updatedAt:null},messages:[{id:crypto.randomUUID(),sender:'Bilio',title:"Bilio'ya hoş geldin!",body:'Kaydolduğunuz için teşekkür ederiz. Bilio dünyasında keyifli oyunlar ve iyi eğlenceler dileriz!',details:'Kayıt ödülleri: 5.000 altın ve 1.000 elmas',createdAt,readAt:null}],notifications:[{id:crypto.randomUUID(),title:'Kayıt ödüllerin hazır!',body:'5.000 altın ve 1.000 elmas hesabına eklendi.',createdAt,readAt:null}]};const sidNew=crypto.randomBytes(32).toString('hex');db.users.push(u);db.sessions[sidNew]={userId:u.id,createdAt:now};try{save()}catch(e){db.users=db.users.filter(x=>x.id!==u.id);delete db.sessions[sidNew];throw e}return send(res,201,{user:publicUser(u)},{'Set-Cookie':`bilio_session=${sidNew}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`})}
 if(url.pathname==='/api/login'&&req.method==='POST'){const ip=req.socket.remoteAddress||'x',now=Date.now(),a=(attempts.get(ip)||[]).filter(t=>now-t<60000);if(a.length>=8)return send(res,429,{error:'Çok fazla giriş denemesi. Biraz sonra tekrar deneyin.'});const b=await body(req),u=db.users.find(x=>x.usernameNormalized===norm(b.username));if(!u||!await verify(String(b.password||''),u.passwordHash)){a.push(now);attempts.set(ip,a);return send(res,401,{error:'Kullanıcı adı veya şifre hatalı.'})}u.lastLoginAt=nowIso();const s=crypto.randomBytes(32).toString('hex');db.sessions[s]={userId:u.id,createdAt:now};save();return send(res,200,{user:publicUser(u)},{'Set-Cookie':`bilio_session=${s}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`})}
 if(url.pathname==='/api/logout'&&req.method==='POST'){if(sid)delete db.sessions[sid];save();return send(res,200,{ok:true},{'Set-Cookie':'bilio_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
 if(url.pathname==='/api/messages'&&req.method==='GET'){if(!me)return send(res,401,{error:'Giriş gerekli.'});return send(res,200,{items:[...me.messages].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}
 if(url.pathname==='/api/notifications'&&req.method==='GET'){if(!me)return send(res,401,{error:'Giriş gerekli.'});return send(res,200,{items:[...me.notifications].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}
 const readMatch=url.pathname.match(/^\/api\/(messages|notifications)\/([^/]+)\/read$/);if(readMatch&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const list=readMatch[1]==='messages'?me.messages:me.notifications,item=list.find(x=>x.id===readMatch[2]);if(!item)return send(res,404,{error:'Kayıt bulunamadı.'});item.readAt||=nowIso();save();return send(res,200,{ok:true,user:publicUser(me)})}
 if(url.pathname==='/api/lobby/messages'&&req.method==='GET'){const limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')||50)));const all=[...db.lobbyMessages,...db.lobbyInvites].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));return send(res,200,{items:all.slice(-limit)})}
 if(url.pathname==='/api/lobby/messages'&&req.method==='POST'){if(!me)return send(res,401,{error:'Lobi sohbetine katılmak için kayıt olmanız veya giriş yapmanız gerekiyor.'});rate('lobby:'+me.id);const c=clean((await body(req)).content,500);if(!c)return send(res,400,{error:'Boş mesaj gönderemezsiniz.'});const item={id:crypto.randomUUID(),kind:'message',userId:me.id,username:me.username,titleId:me.selectedTitleId,avatarUrl:me.profile.avatarUrl||'',content:c,createdAt:nowIso()};db.lobbyMessages.push(item);db.lobbyMessages=db.lobbyMessages.slice(-500);save();broadcast(item);return send(res,201,{item})}
 if(url.pathname==='/api/lobby/invitations/join'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const b=await body(req),inv=db.lobbyInvites.find(x=>x.id===b.inviteId);if(!inv||inv.invite.expiresAt<Date.now())return send(res,410,{error:'Davetin süresi doldu.'});if(inv.invite.game==='VAMPİR KÖYLÜ'){const r=roomByCode(inv.invite.roomCode);if(!r)return send(res,404,{error:'Bu oda artık mevcut değil.'});if(r.matchId)return send(res,409,{error:'Oyun zaten başladı.'});if(r.players.length>=12)return send(res,409,{error:'Oda dolu.'});if(roomForUser(me.id)&&roomForUser(me.id)?.id!==r.id)return send(res,409,{error:'Önce mevcut odanızdan ayrılmalısınız.'});joinRoom(r,me);return send(res,200,{ok:true})}return send(res,409,{error:'Bu oyun daveti şu anda katılıma açık değil.'})}
 if(url.pathname==='/api/leaderboard'&&req.method==='GET'){rollover();const sorted=db.users.filter(u=>u.weekly.score>0).sort((a,b)=>b.weekly.score-a.weekly.score||b.weekly.victories-a.weekly.victories||String(a.weekly.updatedAt||'').localeCompare(String(b.weekly.updatedAt||''))||a.id.localeCompare(b.id));const mapped=sorted.map((u,i)=>({rank:i+1,userId:u.id,username:u.username,score:u.weekly.score,victories:u.weekly.victories,titleId:u.selectedTitleId,avatarUrl:u.profile.avatarUrl||''}));const limit=Math.min(100,Number(url.searchParams.get('limit')||100));return send(res,200,{rows:mapped.slice(0,limit),current:me?mapped.find(x=>x.userId===me.id)||null:null,weekKey:db.meta.weekKey})}
 if(url.pathname==='/api/store/products'&&req.method==='GET'){const category=url.searchParams.get('category')||'EMOJİLER';return send(res,200,{items:catalog.filter(p=>p.category===category).map(p=>productFor(me,p))})}
 if(url.pathname==='/api/store/purchase'&&req.method==='POST'){if(!me)return send(res,401,{error:'Mağazadan alışveriş yapmak için kayıt olmanız veya giriş yapmanız gerekiyor.'});const b=await body(req),p=catalog.find(x=>x.id===b.productId);if(!p)return send(res,404,{error:'Bu öğe artık satışta değil.'});if(p.unlockOnly)return send(res,409,{error:'Bu öğe satın alınamaz.'});if(p.requiredLevel&&me.level<p.requiredLevel)return send(res,409,{error:'Bu öğe için gerekli seviyeye ulaşmadın.'});if(b.requestId&&db.transactions.some(x=>x.requestId===b.requestId))return send(res,200,{user:publicUser(me),duplicate:true});const existing=me.inventory.find(x=>x.productId===p.id);if(existing&&!p.consumable)return send(res,409,{error:'Bu öğeye zaten sahipsin.'});if(me[p.currency]<p.price)return send(res,409,{error:p.currency==='gold'?'Yeterli altının bulunmuyor.':'Yeterli elmasın bulunmuyor.'});const backup=JSON.stringify({gold:me.gold,diamonds:me.diamonds,inventory:me.inventory,notifications:me.notifications});try{me[p.currency]-=p.price;if(existing)existing.quantity=(existing.quantity||1)+1;else me.inventory.push({productId:p.id,quantity:1,purchasedAt:nowIso()});db.transactions.push({id:crypto.randomUUID(),requestId:b.requestId||crypto.randomUUID(),userId:me.id,type:'purchase',productId:p.id,amount:p.price,currency:p.currency,createdAt:nowIso()});me.notifications.push({id:crypto.randomUUID(),title:'Satın alma tamamlandı',body:`${p.name} hesabına eklendi.`,createdAt:nowIso(),readAt:null});save()}catch(e){const old=JSON.parse(backup);Object.assign(me,old);throw e}return send(res,200,{user:publicUser(me)})}
 if(url.pathname==='/api/store/equip'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const equipBody=await body(req);const p=catalog.find(x=>x.id===equipBody.productId);if(!p)return send(res,404,{error:'Öğe bulunamadı.'});if(p.category==='UNVANLAR'){if((p.requiredLevel||1)>me.level)return send(res,403,{error:'Bu unvan henüz açılmadı.'});me.selectedTitleId=p.id}else if(p.category==='ÇERÇEVELER'){if(!me.inventory.some(x=>x.productId===p.id))return send(res,403,{error:'Bu çerçeveye sahip değilsin.'});me.profile.selectedFrameId=p.id}else return send(res,400,{error:'Bu öğe kuşanılamaz.'});save();return send(res,200,{user:publicUser(me)})}
 if(url.pathname==='/api/profile'&&req.method==='GET'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const ownedFrames=me.inventory.map(x=>catalog.find(p=>p.id===x.productId)).filter(p=>p?.category==='ÇERÇEVELER').map(p=>({id:p.id,name:p.name}));return send(res,200,{profile:{username:me.username,createdAt:me.createdAt,level:me.level,xp:me.xp,nextLevelXp:nextLevelXp(me.level),about:me.profile.about,avatarUrl:me.profile.avatarUrl,selectedTitleId:me.selectedTitleId,selectedFrameId:me.profile.selectedFrameId,stats:me.stats,badges:me.profile.badges,gifts:me.profile.gifts,achievements:me.profile.achievements,ownedTitleIds:titleIds(me),ownedFrames}})}
 if(url.pathname==='/api/profile'&&req.method==='PUT'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const b=await body(req);const about=clean(b.about,240);if(b.titleId&&!titleIds(me).includes(b.titleId))return send(res,403,{error:'Bu unvan henüz açılmadı.'});if(b.frameId&&!me.inventory.some(x=>x.productId===b.frameId))return send(res,403,{error:'Bu çerçeveye sahip değilsin.'});if(b.avatarDataUrl){const m=String(b.avatarDataUrl).match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!m)return send(res,400,{error:'Desteklenmeyen dosya türü.'});const buf=Buffer.from(m[2],'base64');if(buf.length>5*1024*1024)return send(res,400,{error:'Dosya boyutu en fazla 5 MB olabilir.'});const mime=m[1],isJpeg=mime==='image/jpeg'&&buf[0]===0xff&&buf[1]===0xd8&&buf[2]===0xff,isPng=mime==='image/png'&&buf.subarray(0,8).toString('hex')==='89504e470d0a1a0a',isWebp=mime==='image/webp'&&buf.subarray(0,4).toString()==='RIFF'&&buf.subarray(8,12).toString()==='WEBP';if(!(isJpeg||isPng||isWebp))return send(res,400,{error:'Desteklenmeyen dosya türü.'});me.profile.avatarUrl=b.avatarDataUrl}me.profile.about=about;if(b.titleId)me.selectedTitleId=b.titleId;me.profile.selectedFrameId=b.frameId||null;save();return send(res,200,{user:publicUser(me)})}

 if(url.pathname==='/api/profile/badges'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const b=await body(req),ids=Array.isArray(b.badgeIds)?b.badgeIds.slice(0,5):[];const owned=new Set(me.profile.badges.filter(x=>x.owned).map(x=>x.id));if(ids.some(id=>!owned.has(id)))return send(res,403,{error:'Sahip olmadığın rozeti vitrine ekleyemezsin.'});for(const badge of me.profile.badges)badge.equipped=ids.includes(badge.id);me.profile.selectedBadgeIds=ids;save();return send(res,200,{ok:true})}

 // Protected Vampire game API: existing behavior retained; only invitation mirrors into global lobby.
 if(!me&&url.pathname.startsWith('/api/game/'))return send(res,401,{error:'Giriş gerekli.'});
 if(url.pathname==='/api/game/vampire/active'&&req.method==='GET'){const r=roomForUser(me.id);return send(res,200,{room:r?publicRoom(r):null,match:r?.matchId?privateMatch(matches.get(r.matchId),me.id):null})}
 if(url.pathname==='/api/game/vampire/create'&&req.method==='POST'){const old=roomForUser(me.id);return send(res,200,{room:publicRoom(old||createRoom(me))})}
 if(url.pathname==='/api/game/vampire/join'&&req.method==='POST'){const b=await body(req),r=roomByCode(b.code);if(!r)return send(res,404,{error:'Oda artık mevcut değil.'});return send(res,200,{room:publicRoom(joinRoom(r,me))})}
 const r=roomForUser(me.id);if(url.pathname==='/api/game/vampire/leave'&&req.method==='POST'){if(r)leaveRoom(r,me.id);return send(res,200,{ok:true})}if(!r)return send(res,404,{error:'Aktif oda yok.'});
 if(url.pathname==='/api/game/vampire/ready'&&req.method==='POST')return send(res,200,{ready:toggleReady(r,me.id),room:publicRoom(r)});
 if(url.pathname==='/api/game/vampire/invite'&&req.method==='POST'){if(r.hostUserId!==me.id)return send(res,403,{error:'Yalnızca kurucu davet gönderebilir.'});if(Date.now()-(r.lastInviteAt||0)<15000)return send(res,429,{error:'Davet için biraz bekle.'});r.lastInviteAt=Date.now();const inv={id:crypto.randomUUID(),game:'VAMPİR KÖYLÜ',roomCode:r.code,inviter:me.username,players:r.players.length,max:12,createdAt:Date.now(),expiresAt:Date.now()+300000};invites.push(inv);const lobby={id:crypto.randomUUID(),kind:'invite',username:me.username,createdAt:nowIso(),invite:{game:'VAMPİR KÖYLÜ',roomCode:r.code,players:r.players.length,max:12,expiresAt:inv.expiresAt}};db.lobbyInvites.push(lobby);save();broadcast(lobby);return send(res,200,{invite:inv})}
 if(url.pathname==='/api/game/vampire/chat'&&req.method==='POST'){rate(`room:${me.id}`);const c=clean((await body(req)).content);if(!c)return send(res,400,{error:'Boş mesaj gönderilemez.'});r.messages.push({id:crypto.randomUUID(),senderUserId:me.id,username:me.username,content:c,createdAt:Date.now()});return send(res,200,{ok:true})}
 if(!r.matchId)return send(res,409,{error:'Maç başlamadı.'});const m=matches.get(r.matchId),p=m.players[me.id];
 if(url.pathname==='/api/game/vampire/action'&&req.method==='POST'){const b=await body(req);if(m.phase!=='NIGHT'||!p.alive)return send(res,409,{error:'Bu işlem şu anda kullanılamaz.'});const t=m.players[b.targetId];if(!t?.alive)return send(res,400,{error:'Geçersiz hedef.'});if(p.role==='VILLAGER')return send(res,403,{error:'Gece yeteneğin yok.'});if(p.role==='VAMPIRE'&&t.role==='VAMPIRE')return send(res,400,{error:'Vampir takım arkadaşını seçemezsin.'});if(p.role==='SEER'&&b.targetId===me.id)return send(res,400,{error:'Kendini araştıramazsın.'});p.nightTarget=b.targetId;if(p.role==='SEER')return send(res,200,{ok:true,result:t.role==='VAMPIRE'?'VAMPİR':'VAMPİR DEĞİL'});return send(res,200,{ok:true})}
 if(url.pathname==='/api/game/vampire/vampire-chat'&&req.method==='POST'){rate(`vamp:${me.id}`);if(m.phase!=='NIGHT'||!p.alive||p.role!=='VAMPIRE')return send(res,403,{error:'Vampir sohbetine erişemezsin.'});const c=clean((await body(req)).content);if(!c)return send(res,400,{error:'Boş mesaj.'});m.vampireMessages.push({id:crypto.randomUUID(),username:me.username,content:c,createdAt:Date.now()});return send(res,200,{ok:true})}
 if(url.pathname==='/api/game/vampire/village-chat'&&req.method==='POST'){rate(`village:${me.id}`);if(m.phase!=='DAY_DISCUSSION'||!p.alive)return send(res,403,{error:'Şu anda köy sohbetine yazamazsın.'});const c=clean((await body(req)).content);if(!c)return send(res,400,{error:'Boş mesaj.'});m.villageMessages.push({id:crypto.randomUUID(),username:me.username,content:c,createdAt:Date.now()});return send(res,200,{ok:true})}
 if(url.pathname==='/api/game/vampire/vote'&&req.method==='POST'){if(m.phase!=='DAY_VOTING'||!p.alive)return send(res,403,{error:'Oy kullanamazsın.'});const b=await body(req);if(b.abstain)m.votes[me.id]={abstain:true};else{if(b.targetId===me.id||!m.players[b.targetId]?.alive)return send(res,400,{error:'Geçersiz oy hedefi.'});m.votes[me.id]={target:b.targetId,abstain:false}}const living=Object.values(m.players).filter(x=>x.alive).length;if(Object.keys(m.votes).length>=living)finishVote(m);return send(res,200,{ok:true})}
 return send(res,404,{error:'Bulunamadı.'});
}catch(e){send(res,500,{error:e.message||'Sunucu hatası.'})}});
server.listen(PORT,()=>console.log(`Bilio API http://localhost:${PORT}`));
