import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {createRoom,roomByCode,roomForUser,joinRoom,leaveRoom,toggleReady,publicRoom,matches,privateMatch,invites,finishVote,touchPlayer,setSpectating,addDeadMessage,voteProgress,addVampireBots} from './vampire-store.mjs';
import {validateNightAction} from './vampire-engine.mjs';
import {applyXp, rankPlayers} from './bil-bakalim-engine.mjs';
import {bilMatches,createBilRoom,bilRoomByCode,bilRoomForUser,joinBilRoom,leaveBilRoom,updateBilSettings,toggleBilReady,publicBilRoom,publicBilMatch,makeBilSelection,addBilChat,addBilBots} from './bil-bakalim-store.mjs';
import {BOT_PROFILES,botReply} from './bots.mjs';
import {quizRooms,quizRoomForUser,quizRoomByCode,createQuizRoom,joinQuizRoom,leaveQuizRoom,updateQuizSettings,addQuizBots,addQuizChat,startQuiz,answerQuiz,publicQuizRoom} from './quiz-store.mjs';
import {createDonutRewards} from './donut-pack.mjs';

const PORT=Number(process.env.BILIO_API_PORT||8787),dbPath=path.resolve(process.env.BILIO_DB_PATH||'server/data.json');
fs.mkdirSync(path.dirname(dbPath),{recursive:true});let db={users:[],sessions:{},lobbyMessages:[],lobbyInvites:[],transactions:[],weeklyArchives:[],meta:{}};try{db={...db,...JSON.parse(fs.readFileSync(dbPath,'utf8'))}}catch{}
db.users ||= [];db.sessions ||= {};db.lobbyMessages ||= [];db.lobbyInvites ||= [];db.transactions ||= [];db.weeklyArchives ||= [];db.donutPacks ||= [];db.meta ||= {};
const nowIso=()=>new Date().toISOString();
const staticRoot=path.resolve(process.env.BILIO_STATIC_ROOT||'dist-verified');
const mimeTypes={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.webp':'image/webp','.map':'application/json; charset=utf-8'};
function serveStatic(url,res){if(process.env.BILIO_SERVE_STATIC!=='1')return false;let requested=decodeURIComponent(url.pathname);if(requested==='/'||!path.extname(requested))requested='/index.html';const file=path.resolve(staticRoot,`.${requested}`);if(!file.startsWith(staticRoot+path.sep)&&file!==path.join(staticRoot,'index.html'))return false;try{const data=fs.readFileSync(file);res.writeHead(200,{'Content-Type':mimeTypes[path.extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':path.extname(file)==='.html'?'no-cache':'public, max-age=3600'});res.end(data);return true}catch{return false}}
let startupDirty=false;
for(const u of db.users){u.gold??=0;u.diamonds??=0;u.messages??=[];u.notifications??=[];u.friends??=[];u.likesReceived??=[];u.level??=1;u.xp??=0;u.selectedTitleId??='title-1';u.inventory??=[];u.profile??={};u.profile.about??='';u.profile.avatarUrl??='';u.profile.selectedFrameId??=null;u.profile.selectedBadgeIds??=[];u.profile.badges??=[];u.profile.gifts??=[];u.profile.achievements??=[];u.stats??={matches:0,wins:0,correct:0,score:0};u.weekly??={score:0,victories:0,updatedAt:null};if(u.registrationRewardGranted!==true){const createdAt=nowIso();u.gold+=5000;u.diamonds+=1000;u.registrationRewardGranted=true;startupDirty=true;u.messages.push({id:crypto.randomUUID(),sender:'Bilio',title:"Bilio'ya hoş geldin!",body:"Bilio’ya hoş geldin! Kayıt olduğun için teşekkür eder, iyi eğlenceler dileriz.",details:'Kayıt ödüllerin: 5.000 altın ve 1.000 elmas.',createdAt,readAt:null});u.notifications.push({id:crypto.randomUUID(),title:'Kayıt ödüllerin hazır!',body:'5.000 altın ve 1.000 elmas hesabına eklendi.',createdAt,readAt:null});}}
const save=()=>{const tmp=dbPath+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,dbPath)};
if(startupDirty)save();
const reserved=new Set(['admin','administrator','system','biliobot']),attempts=new Map(),rateMap=new Map(),sse=new Set();
const norm=s=>String(s||'').trim().toLocaleLowerCase('tr-TR').replace(/ı/g,'i');
const hash=p=>new Promise((ok,no)=>{const salt=crypto.randomBytes(16);crypto.scrypt(p,salt,64,(e,k)=>e?no(e):ok(`${salt.toString('hex')}:${k.toString('hex')}`))});
const verify=(p,h)=>new Promise(ok=>{const [s,k]=String(h||'').split(':');if(!s||!k)return ok(false);crypto.scrypt(p,Buffer.from(s,'hex'),64,(e,d)=>ok(!e&&d.length===Buffer.from(k,'hex').length&&crypto.timingSafeEqual(d,Buffer.from(k,'hex'))))});
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=')));
const publicUser=u=>({id:u.id,username:u.username,level:u.level,xp:u.xp,selectedTitleId:u.selectedTitleId,gold:u.gold,diamonds:u.diamonds,unreadMessages:u.messages.filter(x=>!x.readAt).length,unreadNotifications:u.notifications.filter(x=>!x.readAt).length});
function send(res,status,obj,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(obj))}
async function body(req,max=8_000_000){let s='';for await(const c of req){s+=c;if(s.length>max)throw Error('İstek çok büyük.')}return JSON.parse(s||'{}')}
const clean=(s,max=500)=>String(s||'').trim().slice(0,max).replace(/[<>]/g,'');
const rate=(key,ms=700,msg='Çok hızlı mesaj gönderiyorsunuz. Lütfen biraz bekleyin.')=>{const n=Date.now(),last=rateMap.get(key)||0;if(n-last<ms)throw Error(msg);rateMap.set(key,n)};
const broadcast=item=>{const data=`data: ${JSON.stringify({type:'lobby-item',item})}\n\n`;for(const r of sse){try{r.write(data)}catch{sse.delete(r)}}};
function currentWeekKey(){const shifted=new Date(Date.now()+3*3600_000),day=(shifted.getUTCDay()+6)%7,monday=new Date(Date.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth(),shifted.getUTCDate()-day));return monday.toISOString().slice(0,10)}
function rollover(){const key=currentWeekKey();if(!db.meta.weekKey){db.meta.weekKey=key;save();return}if(db.meta.weekKey===key)return;const old=db.meta.weekKey;db.weeklyArchives.push({weekKey:old,closedAt:nowIso(),rows:db.users.filter(u=>u.weekly?.score>0).map(u=>({userId:u.id,score:u.weekly.score,victories:u.weekly.victories||0}))});for(const u of db.users)u.weekly={score:0,victories:0,updatedAt:null};db.meta.weekKey=key;save()}
rollover();setInterval(rollover,60_000).unref();
const titleUnlock=id=>{const n=Number(String(id).match(/(\d+)/)?.[1]||1);return n===1?1:(n-1)*20};
const titleIds=u=>Array.from({length:26},(_,i)=>`title-${i+1}`).filter(id=>titleUnlock(id)<=Math.min(500,u.level));
const nextLevelXp=level=>Math.min(500,level)>=500?0:Math.max(1000,level*500-2000);
const titleNames=['ACEMİ','ÇAYLAK','YOLCU','KAŞİF','OYUNCU','YETENEKLİ','USTA','UZMAN','STRATEJİST','BİLGE','ELİT','SEÇKİN','ŞAMPİYON','KAHRAMAN','YILDIZ','EFSANE ADAYI','BÜYÜK USTA','ZİRVE','KOZMİK','KOZMİK II','TAHT VARİSİ','YÜCE','ÖLÜMSÜZ','MİTİK','EFSANEVİ','LEGEND'];
const titleSlugs=['acemi','caylak','yolcu','kasif','oyuncu','yetenekli','usta','uzman','stratejist','bilge','elit','seckin','sampiyon','kahraman','yildiz','efsane-adayi','buyuk-usta','zirve','kozmik','kozmik-2','taht-varisi','yuce','olumsuz','mitik','efsanevi','legend'];
const titleDefinitions=titleNames.map((name,i)=>({id:`title-${i+1}`,category:'UNVANLAR',name,price:0,currency:'gold',preview:'',assetPath:`/titles/assets/title-${String(i+1).padStart(2,'0')}-${titleSlugs[i]}.png`,requiredLevel:i===0?1:i*20,unlockOnly:true,hiddenFromStore:true}));
const badgeRows=[
 ['İlk Adım','İlk maçını tamamla','matches',1],['Oyun Yolcusu','5 maç tamamla','matches',5],['Kararlı Oyuncu','10 maç tamamla','matches',10],['Meydan Okuyan','25 maç tamamla','matches',25],['Deneyimli Yarışmacı','50 maç tamamla','matches',50],['Oyun Tutkunu','100 maç tamamla','matches',100],['Efsane Katılımcı','500 maç tamamla','matches',500],
 ['İlk Zafer','İlk galibiyetini kazan','wins',1],['Kazanan Ruh','5 galibiyet kazan','wins',5],['Zafer Serisi','10 galibiyet kazan','wins',10],['Kupa Avcısı','25 galibiyet kazan','wins',25],['Şampiyon Adayı','50 galibiyet kazan','wins',50],['Büyük Şampiyon','100 galibiyet kazan','wins',100],['Zafer Efsanesi','250 galibiyet kazan','wins',250],
 ['Keskin Zihin','10 doğru cevap ver','correct',10],['Bilgi Toplayıcısı','50 doğru cevap ver','correct',50],['Bilgi Avcısı','100 doğru cevap ver','correct',100],['Soru Ustası','250 doğru cevap ver','correct',250],['Ansiklopedi','500 doğru cevap ver','correct',500],['Bilgelik Kaynağı','1.000 doğru cevap ver','correct',1000],['Üstün Zekâ','2.500 doğru cevap ver','correct',2500],['Bilgi Efsanesi','5.000 doğru cevap ver','correct',5000],
 ['Puan Başlangıcı','1.000 toplam puana ulaş','score',1000],['Puan Biriktirici','5.000 toplam puana ulaş','score',5000],['Puan Ustası','10.000 toplam puana ulaş','score',10000],['Yüksek Skor','25.000 toplam puana ulaş','score',25000],['Altın Skor','50.000 toplam puana ulaş','score',50000],['Skor Şampiyonu','100.000 toplam puana ulaş','score',100000],['Puan İmparatoru','250.000 toplam puana ulaş','score',250000],
 ['Yükselen Yıldız','Seviye 10’a ulaş','level',10],['Parlayan Oyuncu','Seviye 25’e ulaş','level',25],['Ustalık Yolu','Seviye 50’ye ulaş','level',50],['Asırlık Bilge','Seviye 100’e ulaş','level',100],['Seçkin Efsane','Seviye 200’e ulaş','level',200],['Ölümsüz Yolcu','Seviye 350’ye ulaş','level',350],['Bilio Zirvesi','Seviye 500’e ulaş','level',500],
];
const badgeDefinitions=badgeRows.map(([name,requirement,metric,target],i)=>({id:`badge-${String(i+1).padStart(2,'0')}`,category:'ROZETLER',name,price:0,currency:'gold',preview:'',assetPath:`/badges/assets/badge-${String(i+1).padStart(2,'0')}.png`,requirement,metric,target,unlockOnly:true,hiddenFromStore:true}));
const catalog=[
 {id:'emoji-gulen',category:'EMOJİLER',name:'Gülen Donut',price:250,currency:'gold',preview:'🍩'}, {id:'emoji-goz',category:'EMOJİLER',name:'Göz Kırpan',price:200,currency:'gold',preview:'😉'}, {id:'emoji-onay',category:'EMOJİLER',name:'Parmakla Onay',price:200,currency:'gold',preview:'👍'}, {id:'emoji-kalp',category:'EMOJİLER',name:'Kalp',price:150,currency:'gold',preview:'❤️'}, {id:'emoji-parti',category:'EMOJİLER',name:'Parti',price:300,currency:'gold',preview:'🎉'}, {id:'emoji-yildiz',category:'EMOJİLER',name:'Gülen Yıldız',price:250,currency:'gold',preview:'⭐'},
 ...titleDefinitions,
 {id:'frame-baslangic',category:'ÇERÇEVELER',name:'Başlangıç Çerçevesi',price:500,currency:'gold',preview:'◉'}, {id:'frame-karamel',category:'ÇERÇEVELER',name:'Karamel Çerçeve',price:800,currency:'gold',preview:'◎'}, {id:'frame-altin',category:'ÇERÇEVELER',name:'Altın Çerçeve',price:1200,currency:'gold',preview:'◌'}, {id:'frame-gece',category:'ÇERÇEVELER',name:'Gece Çerçevesi',price:950,currency:'gold',preview:'◍'}, {id:'frame-yildiz',category:'ÇERÇEVELER',name:'Yıldız Çerçevesi',price:1400,currency:'gold',preview:'⊙'}, {id:'frame-usta',category:'ÇERÇEVELER',name:'Usta Çerçevesi',price:1800,currency:'gold',preview:'⦿'},
 ...badgeDefinitions,
 {id:'gift-kutu',category:'HEDİYELER',name:'Hediye Kutusu',price:120,currency:'diamonds',preview:'🎁',consumable:true}, {id:'gift-kalp',category:'HEDİYELER',name:'Kalp Hediyesi',price:80,currency:'diamonds',preview:'💝',consumable:true}, {id:'gift-yildiz',category:'HEDİYELER',name:'Yıldız Hediyesi',price:100,currency:'diamonds',preview:'🌟',consumable:true}, {id:'gift-kupa',category:'HEDİYELER',name:'Kupa Hediyesi',price:160,currency:'diamonds',preview:'🏆',consumable:true}, {id:'gift-pasta',category:'HEDİYELER',name:'Kutlama Pastası',price:140,currency:'diamonds',preview:'🎂',consumable:true}, {id:'gift-donut',category:'HEDİYELER',name:'Bilio Donutu',price:90,currency:'diamonds',preview:'🍩',consumable:true},
 {id:'boost-xp',category:'TAKVİYELER',name:'XP Takviyesi',price:200,currency:'diamonds',preview:'⚡',consumable:true}, {id:'boost-puan',category:'TAKVİYELER',name:'Puan Takviyesi',price:180,currency:'diamonds',preview:'✚',consumable:true}, {id:'boost-sure',category:'TAKVİYELER',name:'Süre Takviyesi',price:150,currency:'diamonds',preview:'⏱️',consumable:true}, {id:'boost-seri',category:'TAKVİYELER',name:'Seri Takviyesi',price:220,currency:'diamonds',preview:'🔥',consumable:true}, {id:'boost-koruma',category:'TAKVİYELER',name:'Koruma Takviyesi',price:240,currency:'diamonds',preview:'🛡️',consumable:true}, {id:'boost-sans',category:'TAKVİYELER',name:'Şans Takviyesi',price:260,currency:'diamonds',preview:'🍀',consumable:true}
];
const donutPackProduct={id:'gift-donut-pack',category:'HEDİYELER',name:'Paylaşımlı Donut Paketi',price:5000,currency:'gold',preview:'🍩',consumable:true,requirement:'Lobide paylaşılır; 20 farklı oyuncuya toplam 5.000 elmas dağıtır.'};
catalog.push(donutPackProduct);
const storeProducts=[donutPackProduct];
function badgeOwned(u,id){if(!u)return false;const badge=badgeDefinitions.find(item=>item.id===id);if(!badge)return false;const value=badge.metric==='level'?u.level:Number(u.stats?.[badge.metric]||0);return value>=badge.target}
function productFor(u,p){const inv=u?.inventory?.find(x=>x.productId===p.id);const titleOwned=p.category==='UNVANLAR'&&u&&p.requiredLevel<=u.level;const badge=p.category==='ROZETLER'&&badgeOwned(u,p.id);return {...p,owned:!!inv||!!titleOwned||!!badge,equipped:p.category==='UNVANLAR'?u?.selectedTitleId===p.id:p.category==='ÇERÇEVELER'?u?.profile?.selectedFrameId===p.id:p.category==='ROZETLER'?u?.profile?.selectedBadgeIds?.includes(p.id):false,quantity:inv?.quantity||0}}


function syncDerivedProfile(u){
 const badges=catalog.filter(p=>p.category==='ROZETLER').map(p=>({id:p.id,name:p.name,requirement:p.requirement,assetPath:p.assetPath,owned:badgeOwned(u,p.id),equipped:u.profile.selectedBadgeIds.includes(p.id)}));
 const gifts=u.inventory.map(inv=>{const p=catalog.find(x=>x.id===inv.productId&&x.category==='HEDİYELER');return p?{id:p.id,name:p.name,quantity:inv.quantity||1}:null}).filter(Boolean);
 const achievements=[
  {id:'ach-match-1',name:'İlk Maç',progress:Math.min(u.stats.matches,1),target:1,unlocked:u.stats.matches>=1},
  {id:'ach-win-10',name:'On Galibiyet',progress:Math.min(u.stats.wins,10),target:10,unlocked:u.stats.wins>=10},
  {id:'ach-correct-100',name:'Yüz Doğru Cevap',progress:Math.min(u.stats.correct,100),target:100,unlocked:u.stats.correct>=100},
  {id:'ach-score-10000',name:'On Bin Puan',progress:Math.min(u.stats.score,10000),target:10000,unlocked:u.stats.score>=10000},
 ];
 u.profile.badges=badges;u.profile.gifts=gifts;u.profile.achievements=achievements;
}
function profilePayload(target,viewer){
 syncDerivedProfile(target);
 const ownedFrames=target.inventory.map(x=>catalog.find(p=>p.id===x.productId)).filter(p=>p?.category==='ÇERÇEVELER').map(p=>({id:p.id,name:p.name}));
 return {userId:target.id,username:target.username,createdAt:target.createdAt,level:target.level,xp:target.xp,nextLevelXp:nextLevelXp(target.level),about:target.profile.about,avatarUrl:target.profile.avatarUrl,selectedTitleId:target.selectedTitleId,selectedFrameId:target.profile.selectedFrameId,stats:target.stats,badges:target.profile.badges,gifts:target.profile.gifts,achievements:target.profile.achievements,ownedTitleIds:titleIds(target),ownedFrames,likeCount:(target.likesReceived||[]).length,likedByMe:Boolean(viewer&&(target.likesReceived||[]).includes(viewer.id)),isFriend:Boolean(viewer?.friends?.includes(target.id)),isSelf:viewer?.id===target.id};
}
function grantGameXp(user,gain,score=0,won=false,type='game-reward',matchId=''){
 const requestId=`${type}:${matchId}:${user.id}`;if(db.transactions.some(item=>item.requestId===requestId))return false;
 const next=applyXp(user.level,user.xp,gain);user.level=next.level;user.xp=next.xp;user.stats.matches+=1;user.stats.score+=Math.max(0,score);if(won){user.stats.wins+=1;user.weekly.victories+=1}user.weekly.score+=Math.max(0,score);user.weekly.updatedAt=nowIso();db.transactions.push({id:crypto.randomUUID(),requestId,userId:user.id,type,matchId,xp:gain,createdAt:nowIso()});user.notifications.push({id:crypto.randomUUID(),title:'Maç XP ödülün hazır',body:`Bu maçtan ${gain} XP kazandın.`,createdAt:nowIso(),readAt:null});syncDerivedProfile(user);return true;
}
function settleQuizMatch(room){
 const match=room?.match;if(!match?.finished||match.rewardsApplied)return;const ranking=[...room.players].sort((a,b)=>b.score-a.score||a.seat-b.seat);ranking.forEach((row,index)=>{const user=db.users.find(item=>item.id===row.userId);if(user)grantGameXp(user,Math.max(100,400-index*40),row.score,index===0,'quiz-reward',match.id)});match.rewardsApplied=true;save();
}
function settleVampireMatch(match){
 if(!match||match.phase!=='GAME_OVER'||match.rewardsApplied)return;for(const [userId,player] of Object.entries(match.players)){const user=db.users.find(item=>item.id===userId);if(!user)continue;const won=(match.winner==='VAMPIRE')===(player.role==='VAMPIRE');grantGameXp(user,won?500:250,won?500:200,won,'vampire-reward',match.id)}match.rewardsApplied=true;save();
}
setInterval(()=>{for(const room of quizRooms.values()){publicQuizRoom(room);settleQuizMatch(room)}for(const match of matches.values()){privateMatch(match,Object.keys(match.players)[0]);settleVampireMatch(match)}},1000).unref();
function settleBilMatch(match){
 if(!match||match.status!=='FINISHED'||match.rewardsApplied)return;
 const ranking=rankPlayers(match.players);const now=nowIso();
 for(const row of ranking){const u=db.users.find(x=>x.id===row.userId);if(!u)continue;const txId=`bil-match:${match.id}:${u.id}`;if(db.transactions.some(x=>x.requestId===txId))continue;const next=applyXp(u.level,u.xp,row.xp);u.level=next.level;u.xp=next.xp;u.diamonds+=row.diamonds;u.stats.matches+=1;u.stats.correct+=row.correct;u.stats.score+=row.score;if(row.rank===1){u.stats.wins+=1;u.weekly.victories+=1}u.weekly.score+=row.score;u.weekly.updatedAt=now;db.transactions.push({id:crypto.randomUUID(),requestId:txId,userId:u.id,type:'bil-bakalim-reward',matchId:match.id,diamonds:row.diamonds,xp:row.xp,createdAt:now});u.notifications.push({id:crypto.randomUUID(),title:'Bil Bakalım ödülün hazır',body:`${row.diamonds} elmas ve ${row.xp} XP hesabına eklendi.`,createdAt:now,readAt:null});syncDerivedProfile(u)}
 match.rewardsApplied=true;save();
}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://x');if(!url.pathname.startsWith('/api/'))return serveStatic(url,res)||send(res,404,{error:'Bulunamadı.'});const sid=cookies(req).bilio_session,uid=sid&&db.sessions[sid]?.userId,me=db.users.find(u=>u.id===uid);
 if(url.pathname==='/api/lobby/events'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(': bağlı\n\n');sse.add(res);req.on('close',()=>sse.delete(res));return}
 if(url.pathname==='/api/me'&&req.method==='GET')return me?send(res,200,{user:publicUser(me)}):send(res,401,{error:'Oturum yok.'});
 if(url.pathname==='/api/register'&&req.method==='POST'){const ip=req.socket.remoteAddress||'x',now=Date.now(),key='register:'+ip,a=(attempts.get(key)||[]).filter(t=>now-t<60000);if(a.length>=20)return send(res,429,{error:'Çok fazla kayıt denemesi. Biraz sonra tekrar deneyin.'});a.push(now);attempts.set(key,a);const b=await body(req),raw=String(b.username||'').trim(),n=norm(raw);if(!raw)return send(res,400,{error:'Kullanıcı adı zorunludur.'});if(n.length<3||n.length>20||!/^[-_\p{L}\p{N}]+$/u.test(raw)||reserved.has(n))return send(res,400,{error:'Kullanıcı adı 3–20 karakter olmalı ve harf, rakam, tire veya alt çizgi içermelidir.'});if(db.users.some(u=>u.usernameNormalized===n))return send(res,409,{error:'Bu kullanıcı adı zaten kullanılıyor.'});if(typeof b.password!=='string'||b.password.length<8||b.password.length>128)return send(res,400,{error:'Şifre en az 8 karakter olmalıdır.'});if(b.password!==b.passwordRepeat)return send(res,400,{error:'Şifreler eşleşmiyor.'});const createdAt=nowIso(),u={id:crypto.randomUUID(),username:raw,usernameNormalized:n,passwordHash:await hash(b.password),createdAt,lastLoginAt:createdAt,level:1,xp:0,selectedTitleId:'title-1',gold:5000,diamonds:1000,registrationRewardGranted:true,friends:[],profile:{about:'',avatarUrl:'',selectedFrameId:null,selectedBadgeIds:[],badges:[],gifts:[],achievements:[]},inventory:[],stats:{matches:0,wins:0,correct:0,score:0},weekly:{score:0,victories:0,updatedAt:null},messages:[{id:crypto.randomUUID(),sender:'Bilio',title:"Bilio'ya hoş geldin!",body:"Bilio’ya hoş geldin! Kayıt olduğun için teşekkür eder, iyi eğlenceler dileriz.",details:'Kayıt ödüllerin: 5.000 altın ve 1.000 elmas.',createdAt,readAt:null}],notifications:[{id:crypto.randomUUID(),title:'Kayıt ödüllerin hazır!',body:'5.000 altın ve 1.000 elmas hesabına eklendi.',createdAt,readAt:null}]};const sidNew=crypto.randomBytes(32).toString('hex');db.users.push(u);db.sessions[sidNew]={userId:u.id,createdAt:now};try{save()}catch(e){db.users=db.users.filter(x=>x.id!==u.id);delete db.sessions[sidNew];throw e}return send(res,201,{user:publicUser(u)},{'Set-Cookie':`bilio_session=${sidNew}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`})}
 if(url.pathname==='/api/login'&&req.method==='POST'){const ip=req.socket.remoteAddress||'x',now=Date.now(),a=(attempts.get(ip)||[]).filter(t=>now-t<60000);if(a.length>=8)return send(res,429,{error:'Çok fazla giriş denemesi. Biraz sonra tekrar deneyin.'});const b=await body(req),u=db.users.find(x=>x.usernameNormalized===norm(b.username));if(!u||!await verify(String(b.password||''),u.passwordHash)){a.push(now);attempts.set(ip,a);return send(res,401,{error:'Kullanıcı adı veya şifre hatalı.'})}u.lastLoginAt=nowIso();const s=crypto.randomBytes(32).toString('hex');db.sessions[s]={userId:u.id,createdAt:now};save();return send(res,200,{user:publicUser(u)},{'Set-Cookie':`bilio_session=${s}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`})}
 if(url.pathname==='/api/logout'&&req.method==='POST'){if(sid)delete db.sessions[sid];save();return send(res,200,{ok:true},{'Set-Cookie':'bilio_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
 if(url.pathname==='/api/messages'&&req.method==='GET'){if(!me)return send(res,401,{error:'Giriş gerekli.'});return send(res,200,{items:[...me.messages].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}
 if(url.pathname==='/api/notifications'&&req.method==='GET'){if(!me)return send(res,401,{error:'Giriş gerekli.'});return send(res,200,{items:[...me.notifications].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}
 const readMatch=url.pathname.match(/^\/api\/(messages|notifications)\/([^/]+)\/read$/);if(readMatch&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const list=readMatch[1]==='messages'?me.messages:me.notifications,item=list.find(x=>x.id===readMatch[2]);if(!item)return send(res,404,{error:'Kayıt bulunamadı.'});item.readAt||=nowIso();save();return send(res,200,{ok:true,user:publicUser(me)})}
 if(url.pathname==='/api/lobby/messages'&&req.method==='GET'){const limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')||50)));const all=[...db.lobbyMessages,...db.lobbyInvites].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));return send(res,200,{items:all.slice(-limit)})}
 if(url.pathname==='/api/friends'&&req.method==='GET'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const online=new Set(Object.values(db.sessions).map(session=>session.userId));const items=me.friends.map(id=>db.users.find(user=>user.id===id)).filter(Boolean).map(user=>({userId:user.id,username:user.username,avatarUrl:user.profile.avatarUrl||'',titleId:user.selectedTitleId,online:online.has(user.id),mutualCount:user.friends.filter(id=>me.friends.includes(id)).length}));return send(res,200,{items})}
 if(url.pathname==='/api/friends/add'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const b=await body(req),other=db.users.find(user=>user.id===b.userId);if(!other||other.id===me.id)return send(res,400,{error:'Bu oyuncu arkadaş olarak eklenemez.'});me.friends??=[];other.friends??=[];if(!me.friends.includes(other.id))me.friends.push(other.id);if(!other.friends.includes(me.id))other.friends.push(me.id);save();return send(res,200,{ok:true})}
 const publicProfileMatch=url.pathname.match(/^\/api\/profiles\/([^/]+)$/);if(publicProfileMatch&&req.method==='GET'){const target=db.users.find(user=>user.id===decodeURIComponent(publicProfileMatch[1]));if(!target)return send(res,404,{error:'Oyuncu profili bulunamadı.'});return send(res,200,{profile:profilePayload(target,me)})}
 const profileLikeMatch=url.pathname.match(/^\/api\/profiles\/([^/]+)\/like$/);if(profileLikeMatch&&req.method==='POST'){if(!me)return send(res,401,{error:'Beğeni vermek için giriş yapmalısın.'});const target=db.users.find(user=>user.id===decodeURIComponent(profileLikeMatch[1]));if(!target||target.id===me.id)return send(res,400,{error:'Kendi profiline beğeni veremezsin.'});target.likesReceived??=[];if(target.likesReceived.includes(me.id))return send(res,409,{error:'Bu profile daha önce beğeni verdin.'});target.likesReceived.push(me.id);save();return send(res,200,{likeCount:target.likesReceived.length,likedByMe:true})}
 if(url.pathname==='/api/lobby/messages'&&req.method==='POST'){if(!me)return send(res,401,{error:'Lobi sohbetine katılmak için kayıt olmanız veya giriş yapmanız gerekiyor.'});rate('lobby:'+me.id);const c=clean((await body(req)).content,500);if(!c)return send(res,400,{error:'Boş mesaj gönderemezsiniz.'});const item={id:crypto.randomUUID(),kind:'message',userId:me.id,username:me.username,level:me.level,titleId:me.selectedTitleId,avatarUrl:me.profile.avatarUrl||'',content:c,createdAt:nowIso()};db.lobbyMessages.push(item);db.lobbyMessages=db.lobbyMessages.slice(-500);save();broadcast(item);const reply=botReply(c);if(reply){const bot=BOT_PROFILES[Math.floor(Math.random()*BOT_PROFILES.length)];setTimeout(()=>{const botItem={id:crypto.randomUUID(),kind:'message',userId:bot.id,username:bot.username,level:500,titleId:'bilio-bot',avatarUrl:bot.avatarUrl,content:reply,createdAt:nowIso()};db.lobbyMessages.push(botItem);db.lobbyMessages=db.lobbyMessages.slice(-500);save();broadcast(botItem)},900+Math.floor(Math.random()*1300));}return send(res,201,{item})}
 if(url.pathname==='/api/lobby/donut-packs/share'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});rate(`donut-share:${me.id}`,1500);const inventory=me.inventory.find(item=>item.productId==='gift-donut-pack');if(!inventory?.quantity)return send(res,409,{error:'Paylaşabileceğin bir donut paketin yok.'});inventory.quantity-=1;if(inventory.quantity<=0)me.inventory=me.inventory.filter(item=>item!==inventory);const pack={id:crypto.randomUUID(),ownerId:me.id,ownerUsername:me.username,rewards:createDonutRewards(),claims:[],createdAt:nowIso(),expiresAt:Date.now()+24*60*60*1000};db.donutPacks.push(pack);const item={id:`donut:${pack.id}`,kind:'donut-pack',userId:me.id,username:me.username,level:me.level,titleId:me.selectedTitleId,avatarUrl:me.profile.avatarUrl||'',createdAt:pack.createdAt,donutPack:{packId:pack.id,totalDiamonds:5000,claimedCount:0,maxClaims:20,remainingDiamonds:5000,expiresAt:pack.expiresAt}};db.lobbyMessages.push(item);db.lobbyMessages=db.lobbyMessages.slice(-500);save();broadcast(item);return send(res,201,{item,user:publicUser(me)})}
 if(url.pathname==='/api/lobby/donut-packs/claim'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});rate(`donut-claim:${me.id}`,500);const b=await body(req),pack=db.donutPacks.find(item=>item.id===b.packId);if(!pack||pack.expiresAt<Date.now())return send(res,410,{error:'Bu donut paketinin süresi doldu.'});if(pack.ownerId===me.id)return send(res,409,{error:'Kendi paylaştığın paketten elmas alamazsın.'});if(pack.claims.some(claim=>claim.userId===me.id))return send(res,409,{error:'Bu paketi daha önce açtın.'});if(pack.claims.length>=20)return send(res,409,{error:'Bu donut paketindeki tüm elmaslar dağıtıldı.'});const amount=pack.rewards[pack.claims.length];pack.claims.push({userId:me.id,username:me.username,amount,claimedAt:nowIso()});me.diamonds+=amount;db.transactions.push({id:crypto.randomUUID(),requestId:`donut-claim:${pack.id}:${me.id}`,userId:me.id,type:'donut-pack-claim',packId:pack.id,diamonds:amount,createdAt:nowIso()});me.notifications.push({id:crypto.randomUUID(),title:'Donut paketinden elmas kazandın!',body:`Donut paketinden ${amount} elmas çıktı.`,createdAt:nowIso(),readAt:null});const lobbyItem=db.lobbyMessages.find(item=>item.id===`donut:${pack.id}`);if(lobbyItem)lobbyItem.donutPack={...lobbyItem.donutPack,claimedCount:pack.claims.length,remainingDiamonds:pack.rewards.slice(pack.claims.length).reduce((sum,value)=>sum+value,0)};save();if(lobbyItem)broadcast(lobbyItem);return send(res,200,{amount,user:publicUser(me),donutPack:lobbyItem?.donutPack})}
 if(url.pathname==='/api/lobby/invitations/join'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const b=await body(req),inv=db.lobbyInvites.find(x=>x.id===b.inviteId);if(!inv||inv.invite.expiresAt<Date.now())return send(res,410,{error:'Davetin süresi doldu.'});if(inv.invite.game==='VAMPİR KÖYLÜ'){const r=roomByCode(inv.invite.roomCode);if(!r)return send(res,404,{error:'Bu oda artık mevcut değil.'});if(r.matchId)return send(res,409,{error:'Oyun zaten başladı.'});if(r.players.length>=12)return send(res,409,{error:'Oda dolu.'});if(roomForUser(me.id)&&roomForUser(me.id)?.id!==r.id)return send(res,409,{error:'Önce mevcut odanızdan ayrılmalısınız.'});joinRoom(r,me);return send(res,200,{ok:true})}if(inv.invite.game==='BİL BAKALIM'){const r=bilRoomByCode(inv.invite.roomCode);if(!r)return send(res,404,{error:'Bu oda artık mevcut değil.'});if(r.status!=='LOBBY')return send(res,409,{error:'Oyun zaten başladı.'});if(r.players.length>=r.capacity)return send(res,409,{error:'Oda dolu.'});const current=bilRoomForUser(me.id);if(current&&current.id!==r.id)return send(res,409,{error:'Önce mevcut odanızdan ayrılmalısınız.'});joinBilRoom(r,me);return send(res,200,{ok:true})}return send(res,409,{error:'Bu oyun daveti şu anda katılıma açık değil.'})}
 if(url.pathname==='/api/leaderboard'&&req.method==='GET'){rollover();const sorted=db.users.filter(u=>u.weekly.score>0).sort((a,b)=>b.weekly.score-a.weekly.score||b.weekly.victories-a.weekly.victories||String(a.weekly.updatedAt||'').localeCompare(String(b.weekly.updatedAt||''))||a.id.localeCompare(b.id));const mapped=sorted.map((u,i)=>({rank:i+1,userId:u.id,username:u.username,score:u.weekly.score,victories:u.weekly.victories,level:u.level,titleId:u.selectedTitleId,frameId:u.profile.selectedFrameId,avatarUrl:u.profile.avatarUrl||''}));const limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')||100)));return send(res,200,{rows:mapped.slice(0,limit),current:me?mapped.find(x=>x.userId===me.id)||null:null,weekKey:db.meta.weekKey})}
 if(url.pathname==='/api/store/products'&&req.method==='GET'){const category=url.searchParams.get('category');return send(res,200,{items:storeProducts.filter(p=>!category||p.category===category).map(p=>productFor(me,p))})}
 if(url.pathname==='/api/store/purchase'&&req.method==='POST'&&!storeProducts.length)return send(res,404,{error:'Bu öğe artık satışta değil.'})
 if(url.pathname==='/api/store/purchase'&&req.method==='POST'){if(!me)return send(res,401,{error:'Mağazadan alışveriş yapmak için kayıt olmanız veya giriş yapmanız gerekiyor.'});const b=await body(req),p=storeProducts.find(x=>x.id===b.productId);if(!p)return send(res,404,{error:'Bu öğe artık satışta değil.'});if(p.unlockOnly)return send(res,409,{error:'Bu öğe satın alınamaz.'});if(p.requiredLevel&&me.level<p.requiredLevel)return send(res,409,{error:'Bu öğe için gerekli seviyeye ulaşmadın.'});if(b.requestId&&db.transactions.some(x=>x.requestId===b.requestId))return send(res,200,{user:publicUser(me),duplicate:true});const existing=me.inventory.find(x=>x.productId===p.id);if(existing&&!p.consumable)return send(res,409,{error:'Bu öğeye zaten sahipsin.'});if(me[p.currency]<p.price)return send(res,409,{error:p.currency==='gold'?'Yeterli altının bulunmuyor.':'Yeterli elmasın bulunmuyor.'});const backup=JSON.stringify({gold:me.gold,diamonds:me.diamonds,inventory:me.inventory,notifications:me.notifications});try{me[p.currency]-=p.price;if(existing)existing.quantity=(existing.quantity||1)+1;else me.inventory.push({productId:p.id,quantity:1,purchasedAt:nowIso()});db.transactions.push({id:crypto.randomUUID(),requestId:b.requestId||crypto.randomUUID(),userId:me.id,type:'purchase',productId:p.id,amount:p.price,currency:p.currency,createdAt:nowIso()});me.notifications.push({id:crypto.randomUUID(),title:'Satın alma tamamlandı',body:`${p.name} hesabına eklendi.`,createdAt:nowIso(),readAt:null});save()}catch(e){const old=JSON.parse(backup);Object.assign(me,old);throw e}return send(res,200,{user:publicUser(me)})}
 if(url.pathname==='/api/store/equip'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const equipBody=await body(req);const p=catalog.find(x=>x.id===equipBody.productId);if(!p)return send(res,404,{error:'Öğe bulunamadı.'});if(p.category==='UNVANLAR'){if((p.requiredLevel||1)>me.level)return send(res,403,{error:'Bu unvan henüz açılmadı.'});me.selectedTitleId=p.id}else if(p.category==='ÇERÇEVELER'){if(!me.inventory.some(x=>x.productId===p.id))return send(res,403,{error:'Bu çerçeveye sahip değilsin.'});me.profile.selectedFrameId=p.id}else return send(res,400,{error:'Bu öğe kuşanılamaz.'});save();return send(res,200,{user:publicUser(me)})}
 if(url.pathname==='/api/profile'&&req.method==='GET'){if(!me)return send(res,401,{error:'Giriş gerekli.'});return send(res,200,{profile:profilePayload(me,me)})}
 if(url.pathname==='/api/profile'&&req.method==='PUT'){if(!me)return send(res,401,{error:'Giriş gerekli.'});const b=await body(req);const about=clean(b.about,240);if(b.titleId&&!titleIds(me).includes(b.titleId))return send(res,403,{error:'Bu unvan henüz açılmadı.'});if(b.frameId&&!me.inventory.some(x=>x.productId===b.frameId))return send(res,403,{error:'Bu çerçeveye sahip değilsin.'});if(b.avatarDataUrl){const m=String(b.avatarDataUrl).match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!m)return send(res,400,{error:'Desteklenmeyen dosya türü.'});const buf=Buffer.from(m[2],'base64');if(buf.length>5*1024*1024)return send(res,400,{error:'Dosya boyutu en fazla 5 MB olabilir.'});const mime=m[1],isJpeg=mime==='image/jpeg'&&buf[0]===0xff&&buf[1]===0xd8&&buf[2]===0xff,isPng=mime==='image/png'&&buf.subarray(0,8).toString('hex')==='89504e470d0a1a0a',isWebp=mime==='image/webp'&&buf.subarray(0,4).toString()==='RIFF'&&buf.subarray(8,12).toString()==='WEBP';if(!(isJpeg||isPng||isWebp))return send(res,400,{error:'Desteklenmeyen dosya türü.'});me.profile.avatarUrl=b.avatarDataUrl}me.profile.about=about;if(b.titleId)me.selectedTitleId=b.titleId;me.profile.selectedFrameId=b.frameId||null;save();return send(res,200,{user:publicUser(me)})}

 if(url.pathname==='/api/profile/badges'&&req.method==='POST'){if(!me)return send(res,401,{error:'Giriş gerekli.'});syncDerivedProfile(me);const b=await body(req),ids=Array.isArray(b.badgeIds)?b.badgeIds.slice(0,5):[];const owned=new Set(me.profile.badges.filter(x=>x.owned).map(x=>x.id));if(ids.some(id=>!owned.has(id)))return send(res,403,{error:'Sahip olmadığın rozeti vitrine ekleyemezsin.'});for(const badge of me.profile.badges)badge.equipped=ids.includes(badge.id);me.profile.selectedBadgeIds=ids;save();return send(res,200,{ok:true})}


 if(url.pathname.startsWith('/api/game/quiz/')){if(!me)return send(res,401,{error:'Giriş gerekli.'});const parts=url.pathname.split('/'),kind=parts[4],action=parts[5]||'active';let room=quizRoomForUser(me.id,kind);if(action==='active'&&req.method==='GET')return send(res,200,{room:room?publicQuizRoom(room):null});if(action==='create'&&req.method==='POST'){room=createQuizRoom(kind,me);return send(res,200,{room:publicQuizRoom(room)})}if(action==='join'&&req.method==='POST'){const b=await body(req),target=quizRoomByCode(b.code);if(!target||target.kind!==kind)return send(res,404,{error:'Oda bulunamadı.'});if(room&&room.id!==target.id)leaveQuizRoom(room,me.id);room=joinQuizRoom(target,me);return send(res,200,{room:publicQuizRoom(room)})}if(!room)return send(res,404,{error:'Aktif oda yok.'});if(action==='leave'&&req.method==='POST'){leaveQuizRoom(room,me.id);return send(res,200,{ok:true})}if(action==='settings'&&req.method==='POST')return send(res,200,{room:publicQuizRoom(updateQuizSettings(room,me.id,await body(req)))});if(action==='invite-bots'&&req.method==='POST'){const added=addQuizBots(room,me.id);return send(res,200,{added,room:publicQuizRoom(room)})}if(action==='chat'&&req.method==='POST'){rate(`quiz:${me.id}`);const b=await body(req);return send(res,200,{room:publicQuizRoom(addQuizChat(room,me,b.content))})}if(action==='start'&&req.method==='POST')return send(res,200,{room:publicQuizRoom(startQuiz(room,me.id))});if(action==='answer'&&req.method==='POST'){const b=await body(req),correct=answerQuiz(room,me.id,b.questionIndex,b.choice);return send(res,200,{correct,room:publicQuizRoom(room)})}return send(res,404,{error:'Quiz işlemi bulunamadı.'})}

 // Bil Bakalım uses only authenticated, real room members. Server is authoritative for room state, board, turns and rewards.
 if(!me&&url.pathname.startsWith('/api/game/bil-bakalim'))return send(res,401,{error:'Giriş gerekli.'});
 if(url.pathname==='/api/game/bil-bakalim/active'&&req.method==='GET'){const room=bilRoomForUser(me.id);if(!room)return send(res,200,{room:null,match:null});const roomState=publicBilRoom(room);const match=room.matchId?bilMatches.get(room.matchId):null;if(match?.status==='FINISHED')settleBilMatch(match);return send(res,200,{room:roomState,match:match?publicBilMatch(match):null,user:publicUser(me)})}
 if(url.pathname==='/api/game/bil-bakalim/create'&&req.method==='POST'){const old=bilRoomForUser(me.id);const room=old||createBilRoom(me);return send(res,200,{room:publicBilRoom(room)})}
 if(url.pathname==='/api/game/bil-bakalim/join'&&req.method==='POST'){const b=await body(req),room=bilRoomByCode(b.code);if(!room)return send(res,404,{error:'Bu oda artık mevcut değil.'});const current=bilRoomForUser(me.id);if(current&&current.id!==room.id)return send(res,409,{error:'Önce mevcut odanızdan ayrılmalısınız.'});return send(res,200,{room:publicBilRoom(joinBilRoom(room,me))})}
 if(url.pathname==='/api/game/bil-bakalim/leave'&&req.method==='POST'){const room=bilRoomForUser(me.id);if(room)leaveBilRoom(room,me.id);return send(res,200,{ok:true})}
 if(url.pathname==='/api/game/bil-bakalim/settings'&&req.method==='POST'){const room=bilRoomForUser(me.id);if(!room)return send(res,404,{error:'Aktif oda yok.'});if(room.hostUserId!==me.id)return send(res,403,{error:'Oda ayarlarını yalnızca kurucu değiştirebilir.'});const b=await body(req);return send(res,200,{room:publicBilRoom(updateBilSettings(room,me.id,b))})}
 if(url.pathname==='/api/game/bil-bakalim/ready'&&req.method==='POST'){const room=bilRoomForUser(me.id);if(!room)return send(res,404,{error:'Aktif oda yok.'});return send(res,200,{ready:toggleBilReady(room,me.id),room:publicBilRoom(room)})}
 if(url.pathname==='/api/game/bil-bakalim/chat'&&req.method==='POST'){const room=bilRoomForUser(me.id);if(!room)return send(res,404,{error:'Aktif oda yok.'});rate(`bil-room:${me.id}`);const c=clean((await body(req)).content,500);if(!c)return send(res,400,{error:'Boş mesaj gönderemezsiniz.'});return send(res,201,{item:addBilChat(room,me.id,c),room:publicBilRoom(room)})}
 if(url.pathname==='/api/game/bil-bakalim/invite'&&req.method==='POST'){const room=bilRoomForUser(me.id);if(!room)return send(res,404,{error:'Aktif oda yok.'});if(room.hostUserId!==me.id)return send(res,403,{error:'Yalnızca kurucu davet gönderebilir.'});if(Date.now()-room.lastInviteAt<15000)return send(res,429,{error:'Davet için biraz bekle.'});room.lastInviteAt=Date.now();const lobby={id:crypto.randomUUID(),kind:'invite',username:me.username,createdAt:nowIso(),invite:{game:'BİL BAKALIM',roomCode:room.code,players:room.players.length,max:room.capacity,expiresAt:Date.now()+300000}};db.lobbyInvites.push(lobby);save();broadcast(lobby);return send(res,200,{invite:lobby.invite})}
 if(url.pathname==='/api/game/bil-bakalim/invite-bots'&&req.method==='POST'){const room=bilRoomForUser(me.id);if(!room)return send(res,404,{error:'Aktif oda yok.'});if(room.hostUserId!==me.id)return send(res,403,{error:'Yalnızca kurucu bot davet edebilir.'});const added=addBilBots(room);return send(res,200,{added,room:publicBilRoom(room)})}
 if(url.pathname==='/api/game/bil-bakalim/select'&&req.method==='POST'){const room=bilRoomForUser(me.id);if(!room?.matchId)return send(res,404,{error:'Aktif maç yok.'});const match=bilMatches.get(room.matchId);const b=await body(req);const result=makeBilSelection(match,me.id,b.start,b.end,b.requestId||crypto.randomUUID());if(match.status==='FINISHED')settleBilMatch(match);return send(res,200,{result,match:publicBilMatch(match),user:publicUser(me)})}
 // Protected Vampire game API. Match decisions and channel authorization stay server-authoritative.
 if(!me&&url.pathname.startsWith('/api/game/'))return send(res,401,{error:'Giriş gerekli.'});
 if(url.pathname==='/api/game/vampire/active'&&req.method==='GET'){const r=roomForUser(me.id);if(r)touchPlayer(r,me);return send(res,200,{room:r?publicRoom(r):null,match:r?.matchId?privateMatch(matches.get(r.matchId),me.id):null})}
 if(url.pathname==='/api/game/vampire/create'&&req.method==='POST'){const old=roomForUser(me.id),r=old||createRoom(me);touchPlayer(r,me);return send(res,200,{room:publicRoom(r)})}
 if(url.pathname==='/api/game/vampire/join'&&req.method==='POST'){const b=await body(req),r=roomByCode(b.code);if(!r)return send(res,404,{error:'Oda artık mevcut değil.'});const current=roomForUser(me.id);if(current&&current.id!==r.id)return send(res,409,{error:'Önce mevcut odandan ayrılmalısın.'});const joined=joinRoom(r,me);touchPlayer(joined,me);return send(res,200,{room:publicRoom(joined)})}
 const r=roomForUser(me.id);if(url.pathname==='/api/game/vampire/leave'&&req.method==='POST'){if(r)leaveRoom(r,me.id);return send(res,200,{ok:true})}if(!r)return send(res,404,{error:'Aktif oda yok.'});
 touchPlayer(r,me);
 if(url.pathname==='/api/game/vampire/ready'&&req.method==='POST')return send(res,200,{ready:toggleReady(r,me.id),room:publicRoom(r)});
 if(url.pathname==='/api/game/vampire/spectate'&&req.method==='POST'){try{setSpectating(r,me.id);return send(res,200,{ok:true})}catch(error){return send(res,409,{error:error.message})}}
 if(url.pathname==='/api/game/vampire/invite'&&req.method==='POST'){if(r.hostUserId!==me.id)return send(res,403,{error:'Yalnızca kurucu davet gönderebilir.'});if(Date.now()-(r.lastInviteAt||0)<15000)return send(res,429,{error:'Davet için biraz bekle.'});r.lastInviteAt=Date.now();const inv={id:crypto.randomUUID(),game:'VAMPİR KÖYLÜ',roomCode:r.code,inviter:me.username,players:r.players.length,max:12,createdAt:Date.now(),expiresAt:Date.now()+300000};invites.push(inv);const lobby={id:crypto.randomUUID(),kind:'invite',username:me.username,createdAt:nowIso(),invite:{game:'VAMPİR KÖYLÜ',roomCode:r.code,players:r.players.length,max:12,expiresAt:inv.expiresAt}};db.lobbyInvites.push(lobby);save();broadcast(lobby);return send(res,200,{invite:inv})}
 if(url.pathname==='/api/game/vampire/invite-bots'&&req.method==='POST'){if(r.hostUserId!==me.id)return send(res,403,{error:'Yalnızca kurucu bot davet edebilir.'});const added=addVampireBots(r);return send(res,200,{added,room:publicRoom(r)})}
 if(url.pathname==='/api/game/vampire/chat'&&req.method==='POST'){rate(`room:${me.id}`);if(r.status!=='LOBBY')return send(res,403,{error:'Oda sohbeti yalnızca oyun başlamadan önce kullanılabilir.'});const c=clean((await body(req)).content,500);if(!c)return send(res,400,{error:'Boş mesaj gönderilemez.'});r.messages.push({id:crypto.randomUUID(),senderUserId:me.id,username:me.username,content:c,createdAt:Date.now()});return send(res,200,{ok:true})}
 const m=r.matchId&&matches.get(r.matchId),p=m?.players[me.id];if(!m||!p||p.left)return send(res,404,{error:'Aktif maç yok.'});
 if(url.pathname==='/api/game/vampire/action'&&req.method==='POST'){const b=await body(req);if(m.phase!=='NIGHT')return send(res,409,{error:'Bu işlem şu anda kullanılamaz.'});const validation=validateNightAction(m,me.id,b.targetId);if(!validation.ok)return send(res,400,{error:validation.error});const t=m.players[b.targetId];p.nightTarget=b.targetId;if(p.role==='SEER')return send(res,200,{ok:true,result:t.role==='VAMPIRE'?'VAMPİR':'VAMPİR DEĞİL'});return send(res,200,{ok:true})}
 if(url.pathname==='/api/game/vampire/vampire-chat'&&req.method==='POST'){rate(`vamp:${me.id}`);if(m.phase!=='NIGHT'||!p.alive||p.role!=='VAMPIRE')return send(res,403,{error:'Vampir sohbetine erişemezsin.'});const c=clean((await body(req)).content,500);if(!c)return send(res,400,{error:'Boş mesaj gönderilemez.'});m.vampireMessages.push({id:crypto.randomUUID(),senderUserId:me.id,username:me.username,content:c,createdAt:Date.now()});return send(res,200,{ok:true})}
 if(url.pathname==='/api/game/vampire/village-chat'&&req.method==='POST'){rate(`village:${me.id}`);if(!['DAY_DISCUSSION','DAY_VOTING'].includes(m.phase)||!p.alive)return send(res,403,{error:'Şu anda köy sohbetine yazamazsın.'});const c=clean((await body(req)).content,500);if(!c)return send(res,400,{error:'Boş mesaj gönderilemez.'});m.villageMessages.push({id:crypto.randomUUID(),senderUserId:me.id,username:me.username,content:c,createdAt:Date.now()});return send(res,200,{ok:true})}
 if(url.pathname==='/api/game/vampire/dead-chat'&&req.method==='POST'){rate(`dead:${me.id}`);if(p.alive)return send(res,403,{error:'Ölüler sohbetine yalnızca elenen oyuncular erişebilir.'});const c=clean((await body(req)).content,500);if(!c)return send(res,400,{error:'Boş mesaj gönderilemez.'});try{return send(res,200,{ok:true,item:addDeadMessage(m,me.id,c)})}catch(error){return send(res,403,{error:error.message})}}
 if(url.pathname==='/api/game/vampire/vote'&&req.method==='POST'){if(m.phase!=='DAY_VOTING'||!p.alive)return send(res,403,{error:'Oy kullanamazsın.'});const b=await body(req),replaced=Boolean(m.votes[me.id]);if(b.abstain)m.votes[me.id]={abstain:true};else{if(b.targetId===me.id||!m.players[b.targetId]?.alive||m.players[b.targetId]?.left)return send(res,400,{error:'Geçersiz oy hedefi.'});m.votes[me.id]={target:b.targetId,abstain:false}}const progress=voteProgress(m);if(progress.required>0&&progress.completed>=progress.required)finishVote(m);return send(res,200,{ok:true,replaced})}

 return send(res,404,{error:'Bulunamadı.'});
}catch(e){send(res,500,{error:e.message||'Sunucu hatası.'})}});
server.listen(PORT,()=>console.log(`Bilio API http://localhost:${PORT}`));
