import crypto from 'node:crypto';
import {availableBots,botReply} from './bots.mjs';

export const hangmanRooms=new Map();
export const HANGMAN_LETTER_COST=100;
const alphabet='ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ'.split('');
const pools={
  KARIŞIK:[['KAPADOKYA','Türkiye’de turistik bölge'],['TELESKOP','Gökyüzünü inceleyen araç'],['PENGUEN','Uçamayan kutup kuşu'],['ÇİKOLATA','Kakaodan yapılan tatlı'],['BİLGİSAYAR','Elektronik işlem cihazı'],['KÜTÜPHANE','Kitapların bulunduğu yer'],['FOTOĞRAF','Bir anın görüntüsü'],['MACERA','Heyecanlı yolculuk'],['GÖKKUŞAĞI','Yağmurdan sonra görülen renkler'],['KARPUZ','Yaz meyvesi'],['PUSULA','Yön bulmaya yarar'],['ŞAMPİYON','Yarışmanın birincisi'],['MİKROFON','Sesi yükselten araç'],['KARNABAHAR','Beyaz bir sebze'],['KUMANDA','Uzaktan kontrol aracı']],
  HAYVANLAR:[['KANGURU','Yavrusunu kesesinde taşır'],['ZÜRAFA','En uzun boyunlu hayvan'],['KAPLUMBAĞA','Evini sırtında taşır'],['YUNUS','Zeki bir deniz memelisi'],['BUKALEMUN','Renk değiştirebilir'],['GERGEDAN','Burnunda boynuz taşır'],['KELEBEK','Tırtılın dönüşmüş hâli'],['PAPAĞAN','İnsan sesini taklit edebilir'],['AHTAPOT','Sekiz kollu deniz canlısı'],['KARINCA','Koloni hâlinde yaşayan küçük canlı']],
  ŞEHİRLER:[['İSTANBUL','İki kıtayı birleştiren şehir'],['ANTALYA','Akdeniz’in turizm merkezi'],['ESKİŞEHİR','Porsuk Çayı ile bilinir'],['GAZİANTEP','Baklavasıyla ünlü şehir'],['ÇANAKKALE','Boğazı ve tarihiyle bilinir'],['TRABZON','Karadeniz’de bir şehir'],['ŞANLIURFA','Göbeklitepe burada bulunur'],['NEVŞEHİR','Peribacalarıyla bilinir'],['MARDİN','Taş evleriyle ünlüdür'],['BURSA','Uludağ’ın bulunduğu şehir']],
  YİYECEKLER:[['MANTI','Küçük hamur parçalarıyla yapılır'],['BAKLAVA','Şerbetli ve kat kat tatlı'],['KARNIYARIK','Patlıcanla yapılan yemek'],['MERCİMEK','Çorbası çok sevilir'],['LAHMACUN','İnce hamurlu yöresel yemek'],['KUMPİR','İçi doldurulan fırın patates'],['DONDURMA','Soğuk ve tatlı yiyecek'],['MENEMEN','Yumurta ve domatesle yapılır'],['KURABİYE','Fırında pişen küçük tatlı'],['PİDE','Uzun biçimli hamur yemeği']],
};
const normalize=value=>String(value||'').trim().toLocaleUpperCase('tr-TR');
const makePlayer=(user,seat)=>({userId:user.id,username:user.username,avatarUrl:user.profile?.avatarUrl||user.avatarUrl||'',frameId:user.profile?.selectedFrameId||user.frameId||null,titleId:user.selectedTitleId||user.titleId||'title-1',level:Number(user.level)||1,bot:Boolean(user.bot),seat,score:0});
const shuffled=items=>items.map(value=>({value,sort:Math.random()})).sort((a,b)=>a.sort-b.sort).map(item=>item.value);
const nextCode=()=>`AA-${crypto.randomInt(1000,10000)}`;
export const hangmanRoomForUser=userId=>[...hangmanRooms.values()].find(room=>room.players.some(player=>player.userId===userId))||null;
export const hangmanRoomByCode=code=>[...hangmanRooms.values()].find(room=>room.code===normalize(code))||null;
export function createHangmanRoom(user){const old=hangmanRoomForUser(user.id);if(old)return old;let code;do code=nextCode();while(hangmanRoomByCode(code));const room={id:crypto.randomUUID(),code,hostUserId:user.id,status:'LOBBY',capacity:8,category:'KARIŞIK',roundCount:10,turnSeconds:20,players:[makePlayer(user,0)],messages:[],game:null,rewardsSettled:false,createdAt:Date.now()};hangmanRooms.set(room.id,room);return room;}
export function joinHangmanRoom(room,user){if(room.status!=='LOBBY')throw Error('Oyun zaten başladı.');if(room.players.length>=room.capacity)throw Error('Oda dolu.');if(!room.players.some(player=>player.userId===user.id))room.players.push(makePlayer(user,room.players.length));return room;}
export function leaveHangmanRoom(room,userId){room.players=room.players.filter(player=>player.userId!==userId);if(room.hostUserId===userId&&room.players.length)room.hostUserId=room.players[0].userId;if(room.game&&!room.players.some(player=>player.userId===room.game.activeUserId))advanceTurn(room);if(!room.players.some(player=>!player.bot))hangmanRooms.delete(room.id);}
export function updateHangmanSettings(room,userId,changes){if(room.hostUserId!==userId)throw Error('Ayarları yalnızca kurucu değiştirebilir.');if(room.status!=='LOBBY')throw Error('Oyun başladı.');const category=String(changes.category??room.category),roundCount=Number(changes.roundCount??room.roundCount),turnSeconds=Number(changes.turnSeconds??room.turnSeconds);if(!pools[category]||![5,10,15].includes(roundCount)||![15,20,30].includes(turnSeconds))throw Error('Geçersiz oda ayarı.');Object.assign(room,{category,roundCount,turnSeconds});return room;}
export function addHangmanBots(room,userId){if(room.hostUserId!==userId)throw Error('Yalnızca kurucu bot davet edebilir.');if(room.status!=='LOBBY')throw Error('Oyun başladı.');const bots=availableBots(room.players.map(player=>player.userId),room.capacity-room.players.length);for(const bot of bots)room.players.push(makePlayer(bot,room.players.length));return bots.length;}
export function addHangmanChat(room,user,content){const text=String(content||'').trim().slice(0,500);if(!text)throw Error('Boş mesaj gönderilemez.');room.messages.push({id:crypto.randomUUID(),userId:user.id,username:user.username,avatarUrl:user.profile?.avatarUrl||'',bot:false,content:text,createdAt:Date.now()});const reply=botReply(text),bot=room.players.find(player=>player.bot);if(reply&&bot)room.messages.push({id:crypto.randomUUID(),userId:bot.userId,username:bot.username,avatarUrl:bot.avatarUrl,bot:true,content:reply,createdAt:Date.now()+800});room.messages=room.messages.slice(-100);return room;}
function roundData(room,index){const source=pools[room.category]||pools.KARIŞIK;return room.game.words[index%room.game.words.length]||source[index%source.length];}
function masked(word,guessed){return [...word].map(letter=>letter===' '?' ':guessed.includes(letter)?letter:'_').join(' ');}
function activePlayer(room){return room.players.find(player=>player.userId===room.game?.activeUserId);}
function setActive(room,index,time=Date.now()){if(!room.players.length)return;const player=room.players[index%room.players.length];room.game.activeIndex=index%room.players.length;room.game.activeUserId=player.userId;room.game.turnStartedAt=time;room.game.turnEndsAt=time+room.turnSeconds*1000;room.game.botActed=false;}
function advanceTurn(room,time=Date.now()){if(!room.game||room.status!=='PLAYING'||!room.players.length)return;setActive(room,(room.game.activeIndex+1)%room.players.length,time);}
function finishRound(room,time=Date.now(),winnerId=null,points=100){const game=room.game,player=room.players.find(item=>item.userId===(winnerId||game.activeUserId));if(player&&winnerId)player.score+=points;game.roundIndex+=1;if(game.roundIndex>=room.roundCount){game.finished=true;room.status='ENDED';return;}const [word,clue]=roundData(room,game.roundIndex);Object.assign(game,{word,clue,guessed:[],wrong:[],purchasedBy:[]});setActive(room,(game.activeIndex+1)%room.players.length,time);}
export function startHangman(room,userId,time=Date.now()){if(room.hostUserId!==userId)throw Error('Oyunu yalnızca kurucu başlatabilir.');if(room.status!=='LOBBY')throw Error('Oyun zaten başladı.');if(!room.players.length)throw Error('Oyuncu bulunamadı.');const source=pools[room.category]||pools.KARIŞIK,words=shuffled(source);room.players.forEach(player=>{player.score=0});room.status='PLAYING';room.rewardsSettled=false;room.game={roundIndex:0,words,word:words[0][0],clue:words[0][1],guessed:[],wrong:[],purchasedBy:[],activeIndex:0,activeUserId:room.players[0].userId,turnStartedAt:time,turnEndsAt:time+room.turnSeconds*1000,botActed:false,finished:false};return room;}
export function guessHangmanLetter(room,userId,value,time=Date.now()){tickHangman(room,time);const game=room.game;if(!game||room.status!=='PLAYING')throw Error('Aktif oyun yok.');if(game.activeUserId!==userId)throw Error('Sıra sende değil.');const letter=normalize(value);if(!alphabet.includes(letter))throw Error('Geçersiz harf.');if(game.guessed.includes(letter)||game.wrong.includes(letter))throw Error('Bu harf daha önce seçildi.');const player=activePlayer(room),count=[...game.word].filter(item=>item===letter).length;if(count){game.guessed.push(letter);if(player)player.score+=count*25;if(masked(game.word,game.guessed).replaceAll(' ','')===game.word.replaceAll(' ',''))finishRound(room,time,userId,100);else advanceTurn(room,time);}else{game.wrong.push(letter);if(game.wrong.length>=6)finishRound(room,time);else advanceTurn(room,time);}return{correct:count>0,count};}
export function guessHangmanWord(room,userId,value,time=Date.now()){tickHangman(room,time);const game=room.game;if(!game||room.status!=='PLAYING')throw Error('Aktif oyun yok.');if(game.activeUserId!==userId)throw Error('Sıra sende değil.');const answer=normalize(value).replace(/\s+/g,' ');if(answer.length<2)throw Error('Kelime tahmini çok kısa.');const correct=answer===normalize(game.word);if(correct)finishRound(room,time,userId,200);else{game.wrong.push(`TAHMİN:${answer}`);if(game.wrong.length>=6)finishRound(room,time);else advanceTurn(room,time);}return{correct,points:correct?200:0};}
export function buyHangmanLetter(room,userId,time=Date.now()){tickHangman(room,time);const game=room.game;if(!game||room.status!=='PLAYING')throw Error('Aktif oyun yok.');if(game.activeUserId!==userId)throw Error('Sıra sende değil.');game.purchasedBy||=[];if(game.purchasedBy.includes(userId))throw Error('Bu turda harf alma hakkını kullandın.');const options=[...new Set([...game.word].filter(letter=>letter!==' '&&!game.guessed.includes(letter)))];if(!options.length)throw Error('Açılacak harf kalmadı.');const letter=options[crypto.randomInt(0,options.length)];game.purchasedBy.push(userId);game.guessed.push(letter);game.turnStartedAt=time;game.turnEndsAt=time+room.turnSeconds*1000;game.botActed=false;if(masked(game.word,game.guessed).replaceAll(' ','')===game.word.replaceAll(' ',''))finishRound(room,time,userId,100);return{letter,cost:HANGMAN_LETTER_COST};}
export function tickHangman(room,time=Date.now()){const game=room.game;if(!game||room.status!=='PLAYING'||game.finished)return room;if(time>=game.turnEndsAt){advanceTurn(room,time);return room;}const player=activePlayer(room);if(player?.bot&&!game.botActed&&time>=game.turnStartedAt+1200){game.botActed=true;const correct=[...new Set([...game.word].filter(letter=>letter!==' '&&!game.guessed.includes(letter)))],unused=alphabet.filter(letter=>!game.guessed.includes(letter)&&!game.wrong.includes(letter)&&!game.word.includes(letter)),choice=Math.random()<.76&&correct.length?correct[Math.floor(Math.random()*correct.length)]:unused[Math.floor(Math.random()*unused.length)];if(choice)guessHangmanLetter(room,player.userId,choice,time);}return room;}
export function publicHangmanRoom(room){tickHangman(room);const game=room.game;return{id:room.id,code:room.code,hostUserId:room.hostUserId,status:room.status,capacity:room.capacity,category:room.category,roundCount:room.roundCount,turnSeconds:room.turnSeconds,players:room.players.map(player=>({...player})),messages:room.messages.map(message=>({...message})),game:game?{roundIndex:game.roundIndex,roundCount:room.roundCount,clue:game.clue,maskedWord:masked(game.word,game.guessed),guessed:[...game.guessed],wrong:[...game.wrong],purchasedBy:[...(game.purchasedBy||[])],wrongCount:game.wrong.length,maxWrong:6,activeUserId:game.activeUserId,turnEndsAt:game.turnEndsAt,finished:game.finished,answer:room.status==='ENDED'?game.word:undefined}:null};}
