import crypto from 'node:crypto';
import {availableBots,botReply} from './bots.mjs';
import {quizAnswer} from './quiz-answers.mjs';

export const quizRooms=new Map();
const now=()=>Date.now();
const validKinds=new Set(['song','celebrity','streamer']);
const codePrefix={song:'SB',celebrity:'TK',streamer:'YK'};
const playerFrom=(user,seat)=>({userId:user.id,username:user.username,avatarUrl:user.profile?.avatarUrl||user.avatarUrl||'',frameId:user.profile?.selectedFrameId||user.frameId||null,titleId:user.selectedTitleId||user.titleId||'title-1',bot:Boolean(user.bot),ready:Boolean(user.bot),connected:true,seat,score:0});
const makeCode=kind=>`${codePrefix[kind]}-${crypto.randomInt(1000,10000)}`;
export function quizRoomForUser(userId,kind){return[...quizRooms.values()].find(room=>room.kind===kind&&room.players.some(player=>player.userId===userId))||null;}
export function quizRoomByCode(value){return[...quizRooms.values()].find(room=>room.code===String(value||'').trim().toUpperCase())||null;}
export function createQuizRoom(kind,user){if(!validKinds.has(kind))throw Error('Geçersiz oyun.');const old=quizRoomForUser(user.id,kind);if(old)return old;let code;do code=makeCode(kind);while(quizRoomByCode(code));const room={id:crypto.randomUUID(),kind,code,hostUserId:user.id,status:'LOBBY',capacity:8,category:'KARIŞIK',questionCount:10,duration:15,players:[playerFrom(user,0)],messages:[],match:null,createdAt:now()};quizRooms.set(room.id,room);return room;}
export function joinQuizRoom(room,user){if(room.status!=='LOBBY')throw Error('Oyun başladı.');if(room.players.length>=room.capacity)throw Error('Oda dolu.');if(!room.players.some(player=>player.userId===user.id))room.players.push(playerFrom(user,room.players.length));return room;}
export function leaveQuizRoom(room,userId){room.players=room.players.filter(player=>player.userId!==userId);if(room.hostUserId===userId&&room.players.length)room.hostUserId=room.players[0].userId;if(!room.players.some(player=>!player.bot))quizRooms.delete(room.id);}
export function addQuizChat(room,user,content){if(room.status!=='LOBBY')throw Error('Oda sohbeti yalnızca oyun başlamadan önce kullanılabilir.');const text=String(content||'').trim().slice(0,500);if(!text)throw Error('Boş mesaj gönderilemez.');room.messages.push({id:crypto.randomUUID(),userId:user.id,username:user.username,avatarUrl:user.profile?.avatarUrl||'',bot:false,content:text,createdAt:now()});room.messages=room.messages.slice(-100);const reply=botReply(text),bot=room.players.find(player=>player.bot);if(reply&&bot)room.messages.push({id:crypto.randomUUID(),userId:bot.userId,username:bot.username,avatarUrl:bot.avatarUrl,bot:true,content:reply,createdAt:now()+900});return room;}
export function updateQuizSettings(room,userId,changes){if(room.hostUserId!==userId)throw Error('Ayarları yalnızca kurucu değiştirebilir.');if(room.status!=='LOBBY')throw Error('Oyun başladı.');let count=Number(changes.questionCount??room.questionCount);const duration=Number(changes.duration??room.duration),category=String(changes.category??room.category);if(![10,20,30,60].includes(count)||![10,15,20,30].includes(duration)||!['KARIŞIK','TÜRKÇE','YABANCI'].includes(category))throw Error('Geçersiz oda ayarı.');const available=category==='TÜRKÇE'?20:category==='YABANCI'?40:60;if(count>available)count=available===40?30:available;Object.assign(room,{questionCount:count,duration,category});return room;}
export function addQuizBots(room,userId){if(room.hostUserId!==userId)throw Error('Yalnızca kurucu bot davet edebilir.');if(room.status!=='LOBBY')throw Error('Oyun başladı.');const bots=availableBots(room.players.map(player=>player.userId),room.capacity-room.players.length);for(const bot of bots)room.players.push(playerFrom(bot,room.players.length));return bots.length;}
export function startQuiz(room,userId){if(room.hostUserId!==userId)throw Error('Oyunu yalnızca kurucu başlatabilir.');if(room.status!=='LOBBY')throw Error('Oyun zaten başladı.');const startedAt=now();room.status='PLAYING';room.players.forEach(player=>{player.score=0});room.match={id:crypto.randomUUID(),index:0,questionCount:room.questionCount,duration:room.duration,questionStartedAt:startedAt,questionEndsAt:startedAt+room.duration*1000,answers:{},finished:false};return room;}
function advance(room,timestamp=now()){const match=room.match;if(!match||match.finished)return;match.index+=1;match.answers={};if(match.index>=match.questionCount){match.finished=true;room.status='ENDED';return;}match.questionStartedAt=timestamp;match.questionEndsAt=timestamp+match.duration*1000;}
export function tickQuiz(room,timestamp=now()){const match=room.match;if(!match||match.finished)return;for(const player of room.players){if(!player.bot||match.answers[player.userId])continue;const answerAt=match.questionStartedAt+1200+player.seat*420;if(timestamp>=answerAt){const correct=Math.random()>.28;match.answers[player.userId]={correct,at:timestamp};if(correct)player.score+=Math.max(20,100-Math.floor((timestamp-match.questionStartedAt)/1000)*2);}}
 if(timestamp>=match.questionEndsAt||Object.keys(match.answers).length>=room.players.length)advance(room,timestamp);
}
export function answerQuiz(room,userId,questionIndex,choice){tickQuiz(room);const match=room.match;if(!match||match.finished)throw Error('Aktif soru yok.');if(Number(questionIndex)!==match.index)throw Error('Bu soru artık aktif değil.');if(match.answers[userId])throw Error('Bu soruyu zaten cevapladın.');const player=room.players.find(item=>item.userId===userId);if(!player)throw Error('Bu odada değilsin.');const isCorrect=String(choice)===quizAnswer(room.kind,room.category,match.index);match.answers[userId]={correct:isCorrect,at:now()};if(isCorrect)player.score+=Math.max(20,100-Math.floor((match.questionEndsAt-now())/1000)*2);if(Object.keys(match.answers).length>=room.players.length)advance(room);return isCorrect;}
export function publicQuizRoom(room){tickQuiz(room);return{id:room.id,kind:room.kind,code:room.code,hostUserId:room.hostUserId,status:room.status,capacity:room.capacity,category:room.category,questionCount:room.questionCount,duration:room.duration,players:room.players.map(player=>({...player})),messages:(room.messages||[]).map(message=>({...message})),match:room.match?{id:room.match.id,index:room.match.index,questionCount:room.match.questionCount,duration:room.match.duration,questionEndsAt:room.match.questionEndsAt,answeredUserIds:Object.keys(room.match.answers),finished:room.match.finished}:null};}
