import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api,useAuth} from '../auth/auth';
import {titles} from '../data/titles';

type Player={userId:string;username:string;avatarUrl:string;frameId:string|null;titleId:string;level:number;bot:boolean;seat:number;score:number};
type Message={id:string;userId:string;username:string;avatarUrl:string;bot:boolean;content:string;createdAt:number};
type Game={roundIndex:number;roundCount:number;clue:string;maskedWord:string;guessed:string[];wrong:string[];purchasedBy:string[];wrongCount:number;maxWrong:number;activeUserId:string;turnEndsAt:number;finished:boolean;answer?:string};
type Room={id:string;code:string;hostUserId:string;status:'LOBBY'|'PLAYING'|'ENDED';capacity:number;category:string;roundCount:number;turnSeconds:number;players:Player[];messages:Message[];game:Game|null};
const alphabet='ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ'.split('');
const gameApi=async<T,>(action:string,method='GET',data?:unknown)=>api<T>(`/game/hangman/${action}`,{method,body:data?JSON.stringify(data):undefined});
function Title({id}:{id:string}){if(id==='bilio-bot')return <img className="hm-title bot" src="/assets/bilio-logo.png" alt="Bilio botu"/>;const title=titles.find(item=>item.id===id)||titles[0];return <img className="hm-title" src={title.assetPath} alt={`${title.name} unvanı`}/>}
function Avatar({player}:{player:Player}){return <div className={`hm-avatar ${player.frameId==='frame-donut'?'donut':''}`}>{player.avatarUrl?<img src={player.avatarUrl} alt=""/>:player.username.slice(0,1).toLocaleUpperCase('tr-TR')}</div>}
function HangmanDrawing({wrong}:{wrong:number}){return <svg className="hm-drawing" viewBox="0 0 420 420" role="img" aria-label={`${wrong}/6 hata`}><path className="gallows" d="M65 385H280M115 385V45H300M115 95L165 45M300 45V105"/>{wrong>0&&<circle cx="300" cy="142" r="37"/>}{wrong>1&&<path d="M300 179V275"/>}{wrong>2&&<path d="M300 204L245 245"/>}{wrong>3&&<path d="M300 204L355 245"/>}{wrong>4&&<path d="M300 275L255 345"/>}{wrong>5&&<path d="M300 275L345 345"/>}</svg>}
function Chat({room,text,setText,send}:{room:Room;text:string;setText:(value:string)=>void;send:(event:FormEvent)=>void}){return <section className="hm-chat"><h2>ODA SOHBETİ</h2><div className="hm-chat-list">{room.messages.length?room.messages.slice(-30).map(message=><p key={message.id}><span>{message.avatarUrl?<img src={message.avatarUrl} alt=""/>:message.username.slice(0,1)}</span><i><b>{message.username}</b>{message.content}</i></p>):<em>Henüz mesaj yok.</em>}</div><form onSubmit={send}><input aria-label="Sohbet mesajı" value={text} maxLength={500} placeholder="Mesajını yaz…" onChange={event=>setText(event.target.value)}/><button aria-label="Mesaj gönder">➤</button></form></section>}
export default function HangmanGame(){
 const auth=useAuth(),nav=useNavigate(),[room,setRoom]=useState<Room|null>(null),[code,setCode]=useState(''),[text,setText]=useState(''),[wordGuess,setWordGuess]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const load=useCallback(async(create=false)=>{try{let result=await gameApi<{room:Room|null}>('active');if(!result.room&&create)result=await gameApi<{room:Room}>('create','POST');setRoom(result.room);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Adam Asmaca yüklenemedi.')}},[]);
 useEffect(()=>{void load(true);const poll=window.setInterval(()=>void load(false),700),clock=window.setInterval(()=>setNow(Date.now()),250);return()=>{clearInterval(poll);clearInterval(clock)}},[load]);
 const host=room?.hostUserId===auth.user?.id,active=room?.players.find(player=>player.userId===room.game?.activeUserId),mine=active?.userId===auth.user?.id,seconds=room?.game?Math.max(0,Math.ceil((room.game.turnEndsAt-now)/1000)):room?.turnSeconds||20;
 const request=async(action:string,data?:unknown)=>{if(busy)return;setBusy(true);setError('');try{const result=await gameApi<{room:Room;user?:{gold:number};result?:unknown}>(action,'POST',data);setRoom(result.room);if(result.user)auth.patch({gold:result.user.gold});return result}catch(reason){setError(reason instanceof Error?reason.message:'İşlem tamamlanamadı.')}finally{setBusy(false)}};
 const leave=async()=>{await gameApi('leave','POST').catch(()=>undefined);nav('/oyunlar')};
 const send=(event:FormEvent)=>{event.preventDefault();const content=text.trim();if(!content)return;void request('chat',{content}).then(()=>setText(''))};
 const guessWord=(event:FormEvent)=>{event.preventDefault();const word=wordGuess.trim();if(!word)return;void request('guess-word',{word}).then(result=>{if(result)setWordGuess('')})};
 const invite=async()=>{if(!room)return;const url=`${location.origin}/oyun/adam-asmaca?room=${encodeURIComponent(room.code)}`,data={title:'Bilio Adam Asmaca odasına katıl',text:`Adam Asmaca oda kodu: ${room.code}`,url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text}\n${url}`);setError('Davet bağlantısı kopyalandı.')}}catch(reason){if(!(reason instanceof DOMException&&reason.name==='AbortError'))setError('Davet bağlantısı paylaşılamadı.')}};
 const ranking=useMemo(()=>room?[...room.players].sort((a,b)=>b.score-a.score):[],[room]);
 if(!room)return <main className="hm-shell"><div className="hm-loading">{error||'Adam Asmaca hazırlanıyor…'}</div></main>;
 if(room.status==='LOBBY')return <main className="hm-shell hm-lobby"><header><button onClick={()=>void leave()}>←</button><img src="/assets/bilio-logo.png" alt="Bilio"/><h1>ADAM ASMACA</h1><div><small>ODA KODU</small><b>{room.code}</b></div></header><section className="hm-lobby-grid"><div className="hm-lobby-players"><h2>OYUNCULAR {room.players.length}/{room.capacity}</h2><div>{Array.from({length:room.capacity},(_,seat)=>{const player=room.players[seat];return player?<article key={player.userId}><Avatar player={player}/><div><span><b>{player.username}</b><Title id={player.titleId}/></span><small>SV. {player.level} · {player.userId===room.hostUserId?'KURUCU':player.bot?'BOT':'HAZIR'}</small></div></article>:<article className="empty" key={seat}><div className="hm-empty">＋</div><div><b>OYUNCU BEKLENİYOR</b><small>BOŞ KOLTUK</small></div></article>})}</div></div><aside><section className="hm-settings"><h2>ODA AYARLARI</h2><label>ODA KODUYLA KATIL<div><input value={code} placeholder="AA-1234" onChange={event=>setCode(event.target.value.toUpperCase())}/><button disabled={!code.trim()} onClick={()=>void request('join',{code})}>KATIL</button></div></label><label>KATEGORİ<select disabled={!host} value={room.category} onChange={event=>void request('settings',{category:event.target.value})}><option>KARIŞIK</option><option>HAYVANLAR</option><option>ŞEHİRLER</option><option>YİYECEKLER</option></select></label><label>TUR SAYISI<select disabled={!host} value={room.roundCount} onChange={event=>void request('settings',{roundCount:Number(event.target.value)})}><option>5</option><option>10</option><option>15</option></select></label><label>SIRA SÜRESİ<select disabled={!host} value={room.turnSeconds} onChange={event=>void request('settings',{turnSeconds:Number(event.target.value)})}><option>15</option><option>20</option><option>30</option></select></label></section><Chat room={room} text={text} setText={setText} send={send}/></aside></section><footer><div><strong>{room.players.length}/{room.capacity} OYUNCU HAZIR</strong><small>Odayı arkadaşlarınla veya botlarla doldurabilirsin.</small></div><div><button onClick={()=>void invite()}>OYUNCU DAVET ET</button><button disabled={!host||room.players.length>=room.capacity} onClick={()=>void request('invite-bots')}>BOT DAVET ET</button><button className="gold" disabled={!host} onClick={()=>void request('start')}>OYUNU BAŞLAT</button></div></footer>{error&&<div className="hm-toast">{error}</div>}</main>;
 if(room.status==='ENDED')return <main className="hm-shell hm-results"><header><img src="/assets/bilio-logo.png" alt="Bilio"/><h1>ADAM ASMACA SONUÇLARI</h1></header><section><h2>OYUN TAMAMLANDI</h2><div>{ranking.map((player,index)=><article key={player.userId}><b>{index+1}</b><Avatar player={player}/><span>{player.username}<Title id={player.titleId}/></span><strong>{player.score} PUAN</strong></article>)}</div><button onClick={()=>void leave()}>OYUNLARA DÖN</button></section></main>;
 const game=room.game!,bought=game.purchasedBy?.includes(auth.user!.id);return <main className="hm-shell hm-game"><header><button onClick={()=>void leave()}>←</button><img src="/assets/bilio-logo.png" alt="Bilio"/><h1>ADAM ASMACA</h1><div className="hm-timer"><span>{seconds}</span><small>SANİYE</small></div></header><section className="hm-stage"><div className="hm-main"><div className="hm-status"><span>{game.roundIndex+1}/{game.roundCount} TUR</span><b>{active?`${active.username} OYNUYOR`:'SIRA BEKLENİYOR'}</b><span>{game.wrongCount}/{game.maxWrong} HATA</span></div><div className="hm-visual"><HangmanDrawing wrong={game.wrongCount}/><button className="hm-donut" disabled={!mine||busy||bought||auth.user!.gold<100} onClick={()=>void request('buy-letter')}><img src="/assets/nav-donut.png" alt=""/><b>{bought?'HARF ALINDI':'HARF AL'}</b><small>{bought?'BU TUR KULLANILDI':'100 ALTIN'}</small></button></div><div className="hm-clue"><small>İPUCU</small><strong>{game.clue}</strong></div><div className="hm-word" aria-label="Gizli kelime">{game.maskedWord}</div><form className="hm-word-guess" onSubmit={guessWord}><input value={wordGuess} disabled={!mine||busy} maxLength={40} placeholder={mine?'Kelimeyi tahmin et…':'Sıranı bekle…'} onChange={event=>setWordGuess(event.target.value)}/><button disabled={!mine||busy||!wordGuess.trim()}>TAHMİN ET</button></form><div className="hm-keyboard">{alphabet.map(letter=><button key={letter} disabled={!mine||busy||game.guessed.includes(letter)||game.wrong.includes(letter)} className={game.guessed.includes(letter)?'correct':game.wrong.includes(letter)?'wrong':''} onClick={()=>void request('guess',{letter})}>{letter}</button>)}</div></div><aside><section className="hm-game-players"><h2>OYUNCULAR</h2>{room.players.map(player=><article className={player.userId===game.activeUserId?'active':''} key={player.userId}><Avatar player={player}/><div><span><b>{player.username}</b><Title id={player.titleId}/></span><small>SV. {player.level}</small></div><strong>{player.score}</strong></article>)}</section><Chat room={room} text={text} setText={setText} send={send}/></aside></section>{error&&<div className="hm-toast">{error}</div>}</main>;
}
