import {ChangeEvent,PointerEvent,useMemo,useRef,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {useAuth} from '../auth/AuthContext';
import {titles,unlockedTitles} from '../data/titles';

type ProfileState={status:string;avatar:string;title:string;frame:string;badges:string[];giftShowcase:string[];achievementShowcase:string[];friends:string[];requests:string[]};
const KEY='bilio.profile.v1';
const defaults:ProfileState={status:'bilgi güçtür, eğlence özgürlük!\nbilio’da her soru yeni bir macera.',avatar:'',title:'Efsane Bilgini',frame:'Mor Kristal',badges:['Bilgi Yıldızı'],giftShowcase:[],achievementShowcase:['Bilio Ustası','Hız Canavarı'],friends:['MüzikKralı','BilgeAdam','NeşeliPenguen'],requests:[]};
const users=['OyunCanavarı','MüzikKralı','BilgeAdam','NeşeliPenguen','GeceKöylüsü','YayıncıPro','VampirKral','ÇizgiKağan','TahminUstası'];
const gifts=['Mor Hediye','Yıldız Kutusu','Şampiyon Paketi'];
const achievements=['Bilio Ustası','Hız Canavarı','Soru Makinesi','Mükemmeliyetçi','Efsane Serisi'];
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults}}
function save(v:ProfileState){localStorage.setItem(KEY,JSON.stringify(v))}
export default function Profile(){
 const nav=useNavigate(); const {username}=useParams(); const auth=useAuth(); const owner=!!auth.user&&(!username||username===auth.user.username); const level=auth.user?.level||68; const selectedTitle=titles.find(t=>t.id===(auth.user?.selectedTitleId||'title-4'))||titles[0];
 const [p,setP]=useState<ProfileState>(load); const [edit,setEdit]=useState(false); const [draft,setDraft]=useState(p); const [crop,setCrop]=useState<{src:string;zoom:number;x:number;y:number}|null>(null); const [friendOpen,setFriendOpen]=useState(false); const [q,setQ]=useState(''); const [page,setPage]=useState(0); const drag=useRef<{x:number;y:number}|null>(null);
 const update=(v:ProfileState)=>{setP(v);save(v)}; const result=useMemo(()=>q.trim()?users.filter(u=>u.toLocaleLowerCase('tr').includes(q.trim().toLocaleLowerCase('tr'))&&u!=='BilioMaster'):[],[q]);
 const file=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0]; if(!f)return; if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){alert('JPG, PNG veya WEBP ve en fazla 5 MB seçin.');return} const r=new FileReader();r.onload=()=>setCrop({src:String(r.result),zoom:1,x:0,y:0});r.readAsDataURL(f)};
 const cropSave=()=>{if(!crop)return; const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d')!;x.save();x.beginPath();x.arc(256,256,256,0,Math.PI*2);x.clip();const s=Math.max(512/img.width,512/img.height)*crop.zoom;const w=img.width*s,h=img.height*s;x.drawImage(img,(512-w)/2+crop.x,(512-h)/2+crop.y,w,h);x.restore();setDraft({...draft,avatar:c.toDataURL('image/webp',.86)});setCrop(null)};img.src=crop.src};
 const pointerDown=(e:PointerEvent)=>{drag.current={x:e.clientX,y:e.clientY};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}; const pointerMove=(e:PointerEvent)=>{if(!drag.current||!crop)return;setCrop({...crop,x:crop.x+e.clientX-drag.current.x,y:crop.y+e.clientY-drag.current.y});drag.current={x:e.clientX,y:e.clientY}};
 const visible=p.friends.slice(page*3,page*3+3);
 return <div className="profile-page">
  <div className="profile-stage"><img className="profile-reference" src="/references/profil-gorunumu-referans.png" alt="Bilio profil görünümü"/>
   <button className="ph nav-games" aria-label="Oyunlar" onClick={()=>nav('/oyunlar')}/><button className="ph nav-lobby" aria-label="Lobi" onClick={()=>nav('/lobi')}/><button className="ph nav-leader" aria-label="Liderlik tablosu" onClick={()=>nav('/liderlik')}/><button className="ph nav-store" aria-label="Mağaza" onClick={()=>nav('/magaza')}/><button className="ph msg" aria-label="Mesajlar" onClick={()=>nav('/mesajlar')}/><button className="ph notif" aria-label="Bildirimler" onClick={()=>nav('/bildirimler')}/>
   <div className="profile-title-live"><img src={selectedTitle.assetPath} alt={selectedTitle.name+' unvanı'}/></div>{owner&&<button className="profile-edit-pencil" onClick={()=>{setDraft(p);setEdit(true)}} aria-label="Profili düzenle">✎</button>}
   {p.avatar&&<img className="profile-avatar-overlay" src={p.avatar} alt="Profil resmi"/>}
  </div>
  <main className="profile-extra">
   <section><h2>HEDİYE VİTRİNİ <small>{p.giftShowcase.length}/5</small></h2><div className="showcase">{[0,1,2,3,4].map(i=><button key={i} disabled={!owner} onClick={()=>owner&&update({...p,giftShowcase:p.giftShowcase.filter((_,j)=>j!==i)})}>{p.giftShowcase[i]||'Boş yuva'}</button>)}</div>{owner&&<div className="choices">{gifts.map(g=><button key={g} disabled={p.giftShowcase.includes(g)||p.giftShowcase.length>=5} onClick={()=>update({...p,giftShowcase:[...p.giftShowcase,g]})}>+ {g}</button>)}</div>}</section>
   <section><h2>BAŞARIM VİTRİNİ <small>{p.achievementShowcase.length}/5</small></h2><div className="showcase">{[0,1,2,3,4].map(i=><button key={i} disabled={!owner} onClick={()=>owner&&update({...p,achievementShowcase:p.achievementShowcase.filter((_,j)=>j!==i)})}>{p.achievementShowcase[i]||'Boş yuva'}</button>)}</div>{owner&&<div className="choices">{achievements.map(a=><button key={a} disabled={p.achievementShowcase.includes(a)||p.achievementShowcase.length>=5} onClick={()=>update({...p,achievementShowcase:[...p.achievementShowcase,a]})}>+ {a}</button>)}</div>}</section>
   <section><div className="section-head"><h2>ARKADAŞLAR</h2>{owner&&<button className="pink-btn" onClick={()=>setFriendOpen(true)}>＋ ARKADAŞ EKLE</button>}</div><div className="friend-nav"><button onClick={()=>setPage(Math.max(0,page-1))}>‹</button>{visible.map(f=><div className="friend-card" key={f}><b>{f}</b><span>Çevrimiçi</span><button onClick={()=>nav('/profil/'+encodeURIComponent(f))}>Profili gör</button></div>)}<button onClick={()=>setPage(Math.min(Math.max(0,Math.ceil(p.friends.length/3)-1),page+1))}>›</button></div></section>
  </main>
  {edit&&<div className="modal-back"><div className="profile-modal"><h2>Profili Düzenle</h2><label>Bugün ne hissediyorsun?<textarea maxLength={120} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}/></label><label>Profil resmi<input type="file" accept="image/jpeg,image/png,image/webp" onChange={file}/></label><label>Unvan<select value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}>{unlockedTitles(level).map(t=><option key={t.id} value={t.name}>{t.name} — Level {t.unlockLevel}</option>)}</select></label><label>Çerçeve<select value={draft.frame} onChange={e=>setDraft({...draft,frame:e.target.value})}><option>Mor Kristal</option><option>Pembe Efsane</option><option>Mavi Uzman</option></select></label><label>Rozet<select onChange={e=>setDraft({...draft,badges:[e.target.value]})}><option>Bilgi Yıldızı</option><option>Şampiyon</option><option>Müzik Ustası</option></select></label><div className="modal-actions"><button onClick={()=>setEdit(false)}>İptal</button><button className="pink-btn" onClick={()=>{update({...draft,status:draft.status.trim()});setEdit(false)}}>Kaydet</button></div></div></div>}
  {crop&&<div className="modal-back"><div className="profile-modal"><h2>Profil Resmini Ayarla</h2><div className="cropper" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={()=>drag.current=null}><img src={crop.src} style={{transform:`translate(${crop.x}px,${crop.y}px) scale(${crop.zoom})`}}/></div><input type="range" min="1" max="3" step=".05" value={crop.zoom} onChange={e=>setCrop({...crop,zoom:+e.target.value})}/><div className="modal-actions"><button onClick={()=>setCrop(null)}>İptal</button><button className="pink-btn" onClick={cropSave}>Kırpmayı Kullan</button></div></div></div>}
  {friendOpen&&<div className="modal-back"><div className="profile-modal"><h2>Arkadaş Ekle</h2><input autoFocus placeholder="Kullanıcı adı" value={q} onChange={e=>setQ(e.target.value)}/><div className="search-results">{result.map(u=><div key={u}><span>{u}</span><button disabled={p.friends.includes(u)||p.requests.includes(u)} onClick={()=>update({...p,requests:[...p.requests,u]})}>{p.friends.includes(u)?'Arkadaş':p.requests.includes(u)?'İstek gönderildi':'ARKADAŞLIK İSTEĞİ GÖNDER'}</button></div>)}</div><div className="modal-actions"><button onClick={()=>setFriendOpen(false)}>Kapat</button></div></div></div>}
 </div>
}
