import {useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';

type Kind='song'|'celebrity'|'streamer';
const botNames=['Milla<3','Hakan','Mertbabapro','MssSelin','Mr.Felaket','MssFelaket','Masal','Netro','Abady','SultanSülüman'];
const celebrities=`Tarkan|Sezen Aksu|Kenan İmirzalıoğlu|Beren Saat|Kıvanç Tatlıtuğ|Serenay Sarıkaya|Ajda Pekkan|Barış Manço|Cem Yılmaz|Şener Şen|Türkan Şoray|Haluk Bilginer|Demet Evgar|Mabel Matiz|Hadise|Murat Boz|Sertab Erener|Hande Erçel|Burak Özçivit|Neslihan Atagül|Ariana Grande|Dua Lipa|Selena Gomez|Miley Cyrus|Taylor Swift|Beyoncé|Rihanna|Lady Gaga|Billie Eilish|Adele|Bruno Mars|Ed Sheeran|Justin Bieber|Jennifer Lopez|Shakira|The Weeknd|Tom Cruise|Leonardo DiCaprio|Brad Pitt|Angelina Jolie|Scarlett Johansson|Emma Stone|Zendaya|Jenna Ortega|Keanu Reeves|Will Smith|Robert Downey Jr.|Chris Hemsworth|Morgan Freeman|Natalie Portman|Anne Hathaway|Margot Robbie|Ryan Gosling|Johnny Depp|Dwayne Johnson|Gal Gadot|Pedro Pascal|Millie Bobby Brown|Daniel Radcliffe|Emma Watson`.split('|');
const streamers=`Elraenn|Pqueen|Jahrein|Kendine Müzisyen|Tuğkan Gönültaş|wtcN|Mithrain|Unlost|Easter GamersTv|Pintipanda|Can Sungur| Jahrein|Mert Günhan|Elwind|Levo|Kaanflix|Miafitz|Lynx Çerezcioğlu|Enes Batur|Orkun Işıtmak|Ninja|Pokimane|Shroud|xQc|Kai Cenat|IShowSpeed|HasanAbi|Ibai Llanos|Rubius|AuronPlay|Myth|Tfue|Dr Disrespect|Ludwig|Valkyrae|Sykkuno|Amouranth|Summit1g|Sodapoppin|Asmongold|TimTheTatman|Nickmercs|Clix|Bugha|Tarik|TenZ|Faker|Caedrel|Forsen|Lirik|Gaules|Alanzoka|Cellbit|Quackity|TommyInnit|Tubbo|Ranboo|Dream|GeorgeNotFound|Sapnap`.split('|').map(x=>x.trim());
const songs=`Şımarık—Tarkan|Gülümse—Sezen Aksu|Antidepresan—Mabel Matiz|Aşkın Olayım—Simge|Deli—Mor ve Ötesi|Bir Derdim Var—Mor ve Ötesi|Senden Daha Güzel—Duman|Her Şeyi Yak—Duman|Yolla—Tarkan|Everyway That I Can—Sertab Erener|Prenses—Hadise|Janti—Murat Boz|Bangır Bangır—Gülşen|Kuzu Kuzu—Tarkan|Firuze—Sezen Aksu|Islak Islak—Barış Akarsu|Resimdeki Gözyaşları—Cem Karaca|Gülpembe—Barış Manço|Sarı Laleler—MFÖ|Cambaz—Mor ve Ötesi|Blinding Lights—The Weeknd|Flowers—Miley Cyrus|Levitating—Dua Lipa|Bad Guy—Billie Eilish|Rolling in the Deep—Adele|Shape of You—Ed Sheeran|Uptown Funk—Bruno Mars|Halo—Beyoncé|Diamonds—Rihanna|Poker Face—Lady Gaga|Anti-Hero—Taylor Swift|Havana—Camila Cabello|Cheap Thrills—Sia|Roar—Katy Perry|Sorry—Justin Bieber|Counting Stars—OneRepublic|Believer—Imagine Dragons|Numb—Linkin Park|Yellow—Coldplay|Radioactive—Imagine Dragons|Lose Yourself—Eminem|God's Plan—Drake|Old Town Road—Lil Nas X|Industry Baby—Lil Nas X|Rockstar—Post Malone|Sunflower—Post Malone|Without Me—Eminem|HUMBLE.—Kendrick Lamar|SICKO MODE—Travis Scott|Gangsta's Paradise—Coolio|Smells Like Teen Spirit—Nirvana|Bohemian Rhapsody—Queen|Hotel California—Eagles|Back in Black—AC/DC|Sweet Child o' Mine—Guns N' Roses|Dream On—Aerosmith|Zombie—The Cranberries|Creep—Radiohead|The Final Countdown—Europe|Nothing Else Matters—Metallica`.split('|').map(x=>{const [answer,artist]=x.split('—');return{answer,artist}});

function options(answer:string,pool:string[],index:number){const values=[answer];let cursor=index+7;while(values.length<4){const candidate=pool[cursor%pool.length];if(!values.includes(candidate))values.push(candidate);cursor+=11;}return values.sort((a,b)=>((a.length+index*7)%13)-((b.length+index*7)%13));}
export default function QuizGame({kind}:{kind:Kind}){
 const nav=useNavigate(),[started,setStarted]=useState(false),[bots,setBots]=useState<string[]>([]),[index,setIndex]=useState(0),[score,setScore]=useState(0),[seconds,setSeconds]=useState(15),[picked,setPicked]=useState('');
 const title=kind==='song'?'ŞARKIYI BİL':kind==='celebrity'?'TAHMİN ET KİM':'YAYINCI KİM';
 const pool=kind==='celebrity'?celebrities:kind==='streamer'?streamers:songs.map(x=>x.answer);
 const answer=pool[index%pool.length],choices=useMemo(()=>options(answer,pool,index),[answer,index,pool]);
 useEffect(()=>{if(!started||picked)return;const id=window.setInterval(()=>setSeconds(value=>{if(value<=1){setPicked('SÜRE DOLDU');return 0;}return value-1;}),1000);return()=>clearInterval(id)},[started,picked,index]);
 const next=()=>{setIndex(value=>value+1);setSeconds(15);setPicked('')};
 if(!started)return <main className="quiz-shell"><header><button onClick={()=>nav('/oyunlar')}>←</button><img src="/assets/bilio-logo.png" alt="Bilio"/><h1>{title}</h1></header><section className="quiz-lobby"><div><h2>OYUNCULAR {bots.length+1}/8</h2><article className="quiz-player"><b>SEN</b><span>KURUCU</span></article>{bots.map(name=><article className="quiz-player bot" key={name}><b>{name}</b><span>🍩 BİLİO BOTU</span></article>)}</div><aside><h2>ODA AYARLARI</h2><label>Kategori<select><option>KARIŞIK</option><option>TÜRKÇE</option><option>YABANCI</option></select></label><label>Soru sayısı<select><option>10</option><option>20</option><option>30</option></select></label><label>Soru süresi<select><option>15 saniye</option><option>20 saniye</option></select></label><button onClick={()=>setBots(botNames.slice(0,7))} disabled={bots.length===7}>BOT DAVET ET</button><button className="gold" onClick={()=>setStarted(true)}>OYUNU BAŞLAT</button></aside></section></main>;
 const song=songs[index%songs.length];
 return <main className="quiz-shell"><header><button onClick={()=>nav('/oyunlar')}>←</button><img src="/assets/bilio-logo.png" alt="Bilio"/><h1>{title}</h1><strong>{seconds} SN</strong></header><section className="quiz-game"><div className="quiz-top"><b>{index+1} / {pool.length} SORU</b><span>PUAN {score}</span></div>{kind==='song'?<div className="quiz-media song"><h2>Bu şarkının adı nedir?</h2><iframe title="Şarkı oynatıcı" allow="autoplay" src={`https://www.youtube-nocookie.com/embed?listType=search&list=${encodeURIComponent(song.artist+' '+song.answer+' official audio')}`}/></div>:<div className="quiz-media"><img src={`https://en.wikipedia.org/wiki/Special:Redirect/file/${encodeURIComponent(answer+'.jpg')}`} alt="Sorudaki kişi" onError={event=>{event.currentTarget.src='/assets/nav-donut.png'}}/><h2>{kind==='streamer'?'Bu yayıncı kimdir?':'Resimdeki ünlü kimdir?'}</h2></div>}<div className="quiz-answers">{choices.map(choice=><button key={choice} disabled={Boolean(picked)} className={picked?(choice===answer?'correct':choice===picked?'wrong':''):''} onClick={()=>{setPicked(choice);if(choice===answer)setScore(value=>value+100)}}>{choice}</button>)}</div>{picked&&<button className="quiz-next" onClick={next}>{picked===answer?'DOĞRU!':'DOĞRU CEVAP: '+answer} — SONRAKİ</button>}</section></main>;
}
