/*
# Bilio core multiplayer foundation

1. New Tables
- `profiles`: persistent player identity, balances, level, XP, and profile text.
- `rooms`: real game rooms with owner, game type, code, status, and capacity.
- `room_members`: room membership, bot flag, and ready state.
- `lobby_messages`: persistent public lobby chat messages.

2. Security
- RLS is enabled on every table.
- Authenticated users may manage only their profile, their room memberships, and rooms they own.
- Public lobby messages are readable to authenticated users and writable only as the sender.
- Room membership reads are limited to rooms the user belongs to.

3. Important notes
- New accounts receive starter balances through the profile insert trigger.
- Room codes are unique and are generated by the application before insert.
*/

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text NOT NULL UNIQUE,
  about text NOT NULL DEFAULT '',
  avatar_url text,
  level integer NOT NULL DEFAULT 1 CHECK (level >= 1),
  xp integer NOT NULL DEFAULT 0 CHECK (xp >= 0),
  gold integer NOT NULL DEFAULT 5000 CHECK (gold >= 0),
  diamonds integer NOT NULL DEFAULT 1000 CHECK (diamonds >= 0),
  likes integer NOT NULL DEFAULT 0 CHECK (likes >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.rooms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  game_type text NOT NULL,
  code text NOT NULL UNIQUE,
  capacity integer NOT NULL DEFAULT 8 CHECK (capacity BETWEEN 2 AND 12),
  status text NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting', 'playing', 'finished')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.room_members (
  room_id uuid NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  is_bot boolean NOT NULL DEFAULT false,
  ready boolean NOT NULL DEFAULT false,
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.lobby_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 400),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lobby_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_authenticated" ON public.profiles;
CREATE POLICY "profiles_select_authenticated" ON public.profiles FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "profiles_delete_own" ON public.profiles;
CREATE POLICY "profiles_delete_own" ON public.profiles FOR DELETE TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "rooms_select_members" ON public.rooms;
CREATE POLICY "rooms_select_members" ON public.rooms FOR SELECT TO authenticated USING (owner_id = auth.uid() OR EXISTS (SELECT 1 FROM public.room_members m WHERE m.room_id = rooms.id AND m.user_id = auth.uid()));
DROP POLICY IF EXISTS "rooms_insert_own" ON public.rooms;
CREATE POLICY "rooms_insert_own" ON public.rooms FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid());
DROP POLICY IF EXISTS "rooms_update_own" ON public.rooms;
CREATE POLICY "rooms_update_own" ON public.rooms FOR UPDATE TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
DROP POLICY IF EXISTS "rooms_delete_own" ON public.rooms;
CREATE POLICY "rooms_delete_own" ON public.rooms FOR DELETE TO authenticated USING (owner_id = auth.uid());

DROP POLICY IF EXISTS "room_members_select_members" ON public.room_members;
CREATE POLICY "room_members_select_members" ON public.room_members FOR SELECT TO authenticated USING (user_id = auth.uid() OR EXISTS (SELECT 1 FROM public.room_members own WHERE own.room_id = room_members.room_id AND own.user_id = auth.uid()));
DROP POLICY IF EXISTS "room_members_insert_authenticated" ON public.room_members;
CREATE POLICY "room_members_insert_authenticated" ON public.room_members FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "room_members_update_own" ON public.room_members;
CREATE POLICY "room_members_update_own" ON public.room_members FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "room_members_delete_own" ON public.room_members;
CREATE POLICY "room_members_delete_own" ON public.room_members FOR DELETE TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS "lobby_messages_select_authenticated" ON public.lobby_messages;
CREATE POLICY "lobby_messages_select_authenticated" ON public.lobby_messages FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "lobby_messages_insert_own" ON public.lobby_messages;
CREATE POLICY "lobby_messages_insert_own" ON public.lobby_messages FOR INSERT TO authenticated WITH CHECK (sender_id = auth.uid());
DROP POLICY IF EXISTS "lobby_messages_update_own" ON public.lobby_messages;
CREATE POLICY "lobby_messages_update_own" ON public.lobby_messages FOR UPDATE TO authenticated USING (sender_id = auth.uid()) WITH CHECK (sender_id = auth.uid());
DROP POLICY IF EXISTS "lobby_messages_delete_own" ON public.lobby_messages;
CREATE POLICY "lobby_messages_delete_own" ON public.lobby_messages FOR DELETE TO authenticated USING (sender_id = auth.uid());

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username) VALUES (NEW.id, COALESCE(NULLIF(NEW.raw_user_meta_data->>'username', ''), 'Oyuncu')) ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
